src/domains/exchange/components/ExchangeForm/FormStep.blocks.tsx
src/domains/exchange/components/ExchangeForm/__snapshots__/ExchangeForm.test.tsx.snap
src/domains/exchange/pages/ExchangeView/__snapshots__/ExchangeView.test.tsx.snap

refactor: avoid layout jumps when rendering exchange rate skeleton

---

src/domains/dashboard/components/PortfolioBreakdown/PortfolioBreakdown.blocks.tsx
src/domains/dashboard/components/PortfolioBreakdown/PortfolioBreakdown.tsx
src/domains/dashboard/components/PortfolioBreakdown/__snapshots__/PortfolioBreakdown.test.tsx.snap
src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap

fix: adjust responsive styles of portfolio breakdown

---

src/domains/wallet/components/WalletsGroup/WalletsGroup.blocks.tsx
src/domains/wallet/components/WalletsGroup/WalletsGroup.contracts.ts
src/domains/wallet/components/WalletsGroup/WalletsGroupHeader.tsx
src/domains/wallet/pages/WalletGroupPage/__snapshots__/WalletGroupPage.test.tsx.snap

refactor: adjust dynamic border in `WalletsGroupHeader`

---

src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
src/utils/network-utils.ts

Closes https://github.com/ArdentHQ/arkvault/issues/49

fix: assign correct network on wallet import

---

src/app/components/Header/Header.tsx
src/app/components/Header/__snapshots__/Header.test.tsx.snap
src/domains/contact/pages/Contacts/__snapshots__/Contacts.blocks.test.tsx.snap
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
src/domains/vote/components/VotesHeader/__snapshots__/VotesHeader.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap

Closes https://github.com/ArdentHQ/arkvault/issues/33
Fix the header narrow in case there is no wallets (votes section)

fix: set height of responsive page header

---

src/domains/profile/hooks/use-profile-import.ts
src/domains/profile/pages/Welcome/Welcome.tsx

fix: set profile accent color when navigating to profile

---

src/app/App.blocks.tsx
src/app/hooks/use-profile-synchronizer.ts
src/domains/profile/components/ProfileForm/ProfileForm.tsx
src/domains/profile/pages/ImportProfile/ProfileFormStep.tsx

Closes https://github.com/ArdentHQ/arkvault/issues/61

fix: apply accent color during profile import

---

src/app/i18n/common/i18n.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/CsvSettings.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/TransactionExportForm.test.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/hooks/use-delimiter-options.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/hooks/use-transaction-export-form.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.contracts.ts
src/domains/transaction/components/TransactionExportModal/__snapshots__/TransactionExportModal.test.tsx.snap
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-amount-formatter.factory.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-csv-formatter.factory.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-exporter.factory.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-rates.service.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-to-csv-converter.ts

This PR implements the basic export functionality. Fetches all the transactions of the wallet and applies the basic options including:
* Transaction type (all, incoming, outgoing)
* Csv Delimiter
* Header row inclusion
* Transaction ID
* Transaction Dates
* Sender / Recipient
* Crypto Amount 
The remaining date filter, fiat amounts will be handled in a separate PR.
Closes https://app.clickup.com/t/2jfvy7r
Closes https://app.clickup.com/t/2jfw52n
Closes https://app.clickup.com/t/2jfvyf9
Closes https://app.clickup.com/t/2jfvzce
- …

feat: implement wallet transaction exporter

---

src/app/components/Input/InputDate.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/BasicSettings.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/hooks/use-transaction-export-form.ts
src/styles/datepicker.css

refactor: adjust datepicker styles and valid inputs

---

src/domains/transaction/components/TransactionExportModal/TransactionExportModal.contracts.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportSuccess/TransactionExportSuccess.tsx

Closes https://app.clickup.com/t/2jvrmzm

refactor: show actual filename in success toast

---

src/app/components/Dropdown/Dropdown.contracts.ts
src/app/components/Dropdown/Dropdown.helpers.tsx
src/app/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/hooks/use-delimiter-options.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.contracts.ts

Closes https://app.clickup.com/t/2p6gk10

refactor: remove space delimiter and adjust dropdown item styles

---

package.json
pnpm-lock.yaml
src/app/components/QRFileUpload/QRFileUpload.test.tsx
src/app/components/QRFileUpload/QRFileUpload.tsx
src/app/components/QRFileUpload/__snapshots__/QRFileUpload.test.tsx.snap
src/app/components/QRFileUpload/index.ts
src/domains/transaction/components/QrModal/QrModal.test.tsx
src/domains/transaction/components/QrModal/QrModal.tsx
src/domains/transaction/components/QrModal/__snapshots__/QrModal.test.tsx.snap
src/domains/transaction/i18n.ts
src/domains/transaction/pages/SendTransfer/FormStep.tsx
src/domains/transaction/pages/SendTransfer/SendTransfer.QRCode.test.tsx
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.NetworkSelection.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap

Closes https://app.clickup.com/t/2m94q0g

feat: add qr file upload button

---

src/domains/transaction/validations/SendTransfer.ts

https://app.clickup.com/t/2nnggn2

fix: cast amount to number in transfer validation

---

src/app/hooks/use-networks.ts
src/domains/transaction/hooks/use-send-transfer-form.ts

https://app.clickup.com/t/2t1y629

fix: check only available networks when automatically assigning network in transfer form

---

src/app/components/Tabs/Tabs.tsx
src/app/components/Tabs/__snapshots__/Tabs.test.tsx.snap

https://app.clickup.com/t/2q4vt7j

fix: prevent wallet dropdown menu being overlayed by tabs bar in mobile

---

src/app/components/QRModal/QRModal.tsx
src/app/components/QRModal/__snapshots__/QRModal.test.tsx.snap

https://app.clickup.com/t/2n66ecn

fix: correct qr code upload button ui in mobile

---

src/app/hooks/use-search-parameters-validation.ts

https://app.clickup.com/t/2p2t8m7

fix: construct coin instance during deeplink recipient validation

---

.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/format.yml
.github/workflows/test.yml

To keep it in line with what is being used during development

chore: update pnpm to v7 in workflows

---

src/domains/vote/components/VoteList/VoteItem.tsx
src/domains/vote/components/VoteList/VoteItemMobile.tsx
src/domains/vote/components/VoteList/VoteList.contracts.ts
src/domains/vote/components/VoteList/VoteList.tsx

Rendering of the `VoteList` component currently shows an error in the console about missing keys.

fix: adjust vote list rendering to avoid missing key error

---

src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/message/validations/SignMessage.ts

https://app.clickup.com/t/2r7erht

chore: reduce char limit of message signing

---

src/domains/message/pages/SignMessage/SignMessage.tsx

https://app.clickup.com/t/2r7etp1

refactor: break words in ledger details

---

src/app/hooks/use-deeplink.test.tsx
src/app/hooks/use-search-parameters-validation.ts

refactor: truncate nethash in deeplink url validation

---

src/app/hooks/use-deeplink.test.tsx
src/app/hooks/use-search-parameters-validation.test.ts
src/app/hooks/use-search-parameters-validation.ts

https://app.clickup.com/t/2uwtny9

refactor: use default coin value if missing

---

src/app/hooks/use-profile-synchronizer.ts
src/domains/profile/pages/Welcome/Welcome.tsx

fix: sync profile wallets on deeplink validation

---

src/app/components/Notifications/Notifications.tsx
src/app/components/Notifications/hooks/use-notifications.test.tsx

Closes https://app.clickup.com/t/2t8ek00

fix: mark all notifications as read when dropdown is rendered

---

src/domains/wallet/pages/WalletDetails/components/WalletHeaderMobile/WalletHeaderMobile.tsx
src/domains/wallet/pages/WalletDetails/components/WalletHeaderMobile/__snapshots__/WalletHeaderMobile.test.tsx.snap

Closes https://app.clickup.com/t/2ykqfcb

fix: truncate wallet header address using available space in mobile

---

src/domains/profile/hooks/use-welcome-modal.test.tsx
src/domains/profile/hooks/use-welcome-modal.ts
src/utils/migrations/initialize-ark-networks.ts
src/utils/test-helpers.ts

Closes https://app.clickup.com/t/2ykqbbw

refactor: disable welcome modal on preview mode 

---

src/app/__snapshots__/App.test.tsx.snap
src/app/components/TextArea/TextArea.tsx
src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap
src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/transaction/components/ErrorStep/__snapshots__/ErrorStep.test.tsx.snap
src/domains/transaction/components/UnlockTokens/__snapshots__/UnlockTokensModal.test.tsx.snap
src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap

Closes https://app.clickup.com/t/2ttu5dj

fix: adjust textarea size in error steps

---

src/domains/transaction/components/TransactionExportModal/TransactionExportModal.contracts.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.test.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportProgress/TransactionExportProgress.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportSuccess/TransactionExportSuccess.test.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportSuccess/TransactionExportSuccess.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportSuccess/__snapshots__/TransactionExportSuccess.test.tsx.snap
src/domains/transaction/components/TransactionExportModal/__snapshots__/TransactionExportModal.test.tsx.snap
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.test.ts
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-exporter.factory.ts
src/domains/transaction/i18n.ts

https://app.clickup.com/t/2jfw8cu

refactor: show transaction count during export

---

src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.test.tsx
src/domains/transaction/pages/SendVote/SendVote.Combined.test.tsx

Closes https://app.clickup.com/t/2vk0wqw and https://app.clickup.com/t/2vk0xfk

test: fix flaky tests in `SendVote` and `SendRegistration`

---

src/domains/setting/pages/Appearance/__snapshots__/Appearance.test.tsx.snap
src/domains/setting/pages/Export/__snapshots__/Export.test.tsx.snap
src/domains/setting/pages/General/__snapshots__/General.test.tsx.snap
src/domains/setting/pages/Networks/__snapshots__/Networks.test.tsx.snap
src/domains/setting/pages/Password/__snapshots__/Password.test.tsx.snap
src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap

chore: update snapshots in `setting` domain

---

package.json
pnpm-lock.yaml

-   [x] Remove deprecated `nock`
-   [x] Update `socks-proxy-agent`
-   [x] Documentation _(if necessary)_

deps: minor updates

---

.github/labeler.yml
.github/release.yml
.github/workflows/label.yml

Makes for prettier changelogs, in line with the other projects

chore: add labeler and release workflows

---

src/domains/news/components/NewsCard/NewsCardSkeleton.tsx
src/domains/transaction/components/TransactionTable/NotificationTransactionsTable/NotificationTransactionSkeletonRow.tsx
src/domains/transaction/components/TransactionTable/NotificationTransactionsTable/__snapshots__/NotificationTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowSkeleton.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap

Fixes the skeletons of the notifications and transactions table in expanded mode.

fix: more adjustments to circle skeletons

---

src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
src/app/components/Notifications/hooks/use-notifications.ts
src/domains/message/pages/VerifyMessage/VerifyMessage.test.tsx
src/domains/message/pages/VerifyMessage/VerifyMessage.tsx

chore: fix remaining e2e tests and final adjustments

---

src/domains/message/i18n.ts
src/domains/message/pages/VerifyMessage/FormStep.tsx
src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap

Closes https://app.clickup.com/t/37t6g9p

fix: change ordering of fields in verify message form

---

package.json
pnpm-lock.yaml

chore: update `qr-scanner`

---

package.json
pnpm-lock.yaml

chore: update react responsive

---

package.json
pnpm-lock.yaml

chore: update ledger mock package

---

package.json
pnpm-lock.yaml
src/app/i18n/index.ts
src/app/i18n/react-i18next.config.d.ts

chore: update `i18next` dependencies

---

package.json
pnpm-lock.yaml

chore: update i18next

---

src/app/components/Modal/hooks.ts

fix: adjust scrollbar on modal resize

---

src/app/hooks/use-deeplink.test.tsx
src/app/hooks/use-deeplink.ts
src/app/hooks/use-search-parameters-validation.test.ts
src/app/hooks/use-search-parameters-validation.tsx
src/domains/profile/i18n.ts
src/domains/profile/pages/Welcome/Welcome.test.tsx
src/domains/profile/pages/Welcome/Welcome.tsx

Closes https://app.clickup.com/t/8676xzyed
Test by adding the `?page=migration` param to the URL
IN the latest deployment URL (that may change if I push a new commit) is https://arkvault-ibntkskio-ardent.vercel.app/#/?page=migration (you need to add an account first)

feat: add url to direct link migration page

---

src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.test.tsx
src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx
src/domains/migration/hooks/use-meta-mask.test.tsx
src/domains/migration/hooks/use-meta-mask.ts
src/domains/migration/i18n.ts

Closes https://app.clickup.com/t/39xfauf

feat: metamask mobile handling

---

.github/workflows/deps.yml
.ncurc.json

https://app.clickup.com/t/8676y0wm1

chore: setup dependency update workflow

---

.github/workflows/deps.yml

fix: dep workflow yaml formatting

---

.github/workflows/build.yml
.github/workflows/e2e.yml
src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap

Increase the node memory limit on GitHub actions to avoid heap errors while building

chore: try building with increased memory limit

---

.env.example
src/app/contexts/Migration/Migration.tsx
src/domains/migration/components/MigrationSuccessStep/MigrationSuccessStep.tsx
src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsRow.tsx
src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsRowMobile.tsx
src/domains/migration/components/MigrationTransactionsTable/__snapshots__/MigrationTransactionsTable.test.tsx.snap
src/domains/migration/hooks/use-migration-form.ts
src/utils/polygon-migration.test.ts
src/utils/polygon-migration.ts

Closes https://app.clickup.com/t/86774hkx9

feat: provide all migration variables through migration utility module

---

.github/workflows/build.yml
.github/workflows/compress.yml
.github/workflows/deps.yml
.github/workflows/e2e.yml
.github/workflows/format.yml
.github/workflows/label.yml
.github/workflows/test.yml
scripts/generate-test-workflow.js

https://app.clickup.com/t/867748abv

chore: update workflow actions

---

src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx

https://app.clickup.com/t/867753uxz

refactor: use full balance in migration transaction

---

src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsRow.tsx
src/domains/migration/components/MigrationTransactionsTable/__snapshots__/MigrationTransactionsTable.test.tsx.snap

https://app.clickup.com/t/862j31u7a

refactor: add sender avatar to migration transaction table

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMigrationDetails.tsx

https://app.clickup.com/t/861m89m6u

refactor: remove tooltip from migration network icon and reduce chevron size

---

src/app/contexts/Migration/Migration.test.tsx
src/app/contexts/Migration/Migration.tsx
src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsTable.test.tsx
src/domains/migration/components/MigrationTransactionsTable/__snapshots__/MigrationTransactionsTable.test.tsx.snap
src/domains/migration/i18n.ts
src/domains/migration/migration.contracts.ts
src/domains/migration/utils.ts
src/repositories/migration.repository.ts

https://app.clickup.com/t/862j32war

refactor: adjust icon color and tooltip of pending transaction icons

---

src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.test.tsx
src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx
src/domains/migration/hooks/use-meta-mask.test.tsx
src/domains/migration/hooks/use-meta-mask.ts
src/domains/migration/pages/MigrationAdd/MigrationAdd.Error.test.tsx
src/domains/migration/pages/MigrationAdd/MigrationAdd.test.tsx
src/utils/polygon-migration.test.ts
src/utils/polygon-migration.ts

Closes https://app.clickup.com/t/862j31vh7

feat: allow mumbai network

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowMode.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowSender.test.tsx.snap

https://app.clickup.com/t/861m89q7w

refactor: adjustments to migration icon background color

---

src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx

fix: remove duplicated call to `storeTransaction`

---

src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsTable.tsx

https://app.clickup.com/t/86775vn4m

refactor: sort migrations by timestamp

---

src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx

Closes https://app.clickup.com/t/862j36npm

fix: back button bug

---

src/domains/migration/components/MigrationAuthenticationStep/MigrationAuthenticationStep.test.tsx
src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx
src/domains/migration/components/MigrationReviewStep/MigrationReviewStep.test.tsx
src/domains/migration/hooks/use-migration-form.ts
src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx

alternative approach to https://app.clickup.com/t/862j36npm which disables the back button depending only on the form state.

fix: disable back button based on form state

---

src/domains/migration/components/MigrationDisclaimer/__snapshots__/MigrationDisclaimer.test.tsx.snap
src/domains/migration/components/MigrationPendingStep/__snapshots__/MigrationPendingStep.test.tsx.snap
src/domains/migration/i18n.ts
src/domains/profile/components/ProfileForm/ProfileForm.tsx
src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
src/domains/profile/pages/ImportProfile/__snapshots__/ImportProfile.test.tsx.snap
src/domains/profile/pages/ImportProfile/__snapshots__/ProfileFormStep.test.tsx.snap

Closes https://app.clickup.com/t/867773zaa
Closes https://app.clickup.com/t/86776gn12
Closes https://app.clickup.com/t/8676xv582

chore: update terms link, migration step title & disclaimer text

---

src/app/components/Notifications/MigrationTransactionItem.test.tsx
src/app/components/Notifications/MigrationTransactionItem.tsx
src/app/components/Notifications/MigrationTransactionItemMobile.tsx
src/app/components/Notifications/Notifications.contracts.ts
src/app/components/Notifications/Notifications.test.tsx
src/app/components/Notifications/Notifications.tsx
src/app/components/Notifications/NotificationsMigrations.tsx
src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
src/app/components/Notifications/hooks/use-notifications.test.tsx
src/app/components/Notifications/hooks/use-notifications.ts
src/app/contexts/Migration/Migration.test.tsx
src/app/contexts/Migration/Migration.tsx
src/domains/migration/migration.contracts.ts
src/repositories/migration.repository.ts

https://app.clickup.com/t/86776j005

feat: mark migration notification as read and hide

---

src/domains/migration/hooks/use-migration-transactions.ts
src/utils/polygon-migration.test.ts
src/utils/polygon-migration.ts

Closes https://app.clickup.com/t/86776g04v

refactor: improve migration transaction validation

---

src/app/i18n/common/i18n.ts
src/domains/migration/components/MigrationPendingStep/MigrationPendingStep.test.tsx
src/domains/migration/components/MigrationPendingStep/MigrationPendingStep.tsx
src/domains/migration/components/MigrationPendingStep/__snapshots__/MigrationPendingStep.test.tsx.snap
src/domains/migration/i18n.ts
src/domains/migration/pages/Migration/Migration.test.tsx
src/domains/migration/pages/MigrationAdd/MigrationAdd.test.tsx
src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx
src/domains/migration/pages/MigrationDetails/MigrationDetails.test.tsx
src/domains/migration/pages/MigrationDetails/MigrationDetails.tsx

https://app.clickup.com/t/8677930hx

chore: rename back button in migration pending and success steps

---

src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx

https://app.clickup.com/t/867799ngv

fix: don't await ledger connection before setting auth step

---

src/app/components/Spinner/Spinner.styles.ts
src/app/components/Spinner/Spinner.tsx
src/app/components/Spinner/__snapshots__/Spinner.test.tsx.snap
src/domains/exchange/components/ExchangeForm/__snapshots__/ExchangeForm.test.tsx.snap
src/domains/exchange/pages/ExchangeView/__snapshots__/ExchangeView.test.tsx.snap
src/domains/migration/components/MigrationAuthenticationStep/__snapshots__/MigrationAuthenticationStep.test.tsx.snap
src/domains/profile/pages/ImportProfile/__snapshots__/ProcessingImportStep.test.tsx.snap
src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap
src/domains/transaction/components/AuthenticationStep/Ledger/__snapshots__/ListenLedger.test.tsx.snap
src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
src/domains/transaction/components/LedgerConfirmation/__snapshots__/LedgerConfirmation.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap

fix: adjust spinner styles

---

src/domains/migration/hooks/use-migration-transactions.ts
src/domains/migration/pages/Migration/Migration.test.tsx

Closes https://app.clickup.com/t/86777xnac

fix: await profile sync to finish in migration overview page

---

src/domains/dashboard/components/Migration/MigrationBanner.tsx
src/domains/migration/components/MigrationPendingStep/__snapshots__/MigrationPendingStep.test.tsx.snap
src/utils/polygon-migration.test.ts
src/utils/polygon-migration.ts

Closes https://app.clickup.com/t/86779mvu0

refactor: update migration docs url

---

src/app/components/Notifications/hooks/use-notifications.ts

https://app.clickup.com/t/86779aaeg

refactor: show notification indicator for newly confirmed migrations

---

src/domains/migration/components/MigrationSuccessStep/MigrationSuccessStep.tsx
src/domains/migration/components/MigrationSuccessStep/__snapshots__/MigrationSuccessStep.test.tsx.snap
src/domains/transaction/components/Migration/components/MigrationDetailsModal.tsx

Closes https://app.clickup.com/t/862j5nh67

fix: correct polygon avatar in migration success step

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx

Closes https://app.clickup.com/t/862j5nrz3

fix: adjust colors in migration transaction sender icon

---

src/domains/migration/components/MigrationTransactionsTable/__snapshots__/MigrationTransactionsTable.test.tsx.snap

chore: fix failing snapshots

---

src/domains/migration/components/MigrationPendingStep/MigrationPendingStep.test.tsx
src/domains/migration/components/MigrationPendingStep/MigrationPendingStep.tsx
src/domains/migration/components/MigrationPendingStep/__snapshots__/MigrationPendingStep.test.tsx.snap

Closes https://app.clickup.com/t/8677a21a4

fix: correct date in pending migration overview

---

src/app/contexts/Migration/Migration.tsx
src/domains/migration/pages/MigrationAdd/MigrationAdd.test.tsx
src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx

https://app.clickup.com/t/8677a20d3

fix: redirect to success step once confirmed

---

src/domains/migration/components/MigrationTransactionsTable/MigrationTransactionsRowSkeleton.tsx
src/domains/migration/components/MigrationTransactionsTable/__snapshots__/MigrationTransactionsTable.test.tsx.snap

Closes https://app.clickup.com/t/865bmm12p

fix: adjust sizes in migration transaction skeleton

---

src/app/contexts/Migration/Migration.tsx
src/domains/migration/hooks/use-migration-transactions.ts
src/domains/wallet/hooks/use-wallet-actions.ts

Closes https://app.clickup.com/t/862j71e7f

fix: update migration transactions upon wallet removal

---

src/domains/setting/pages/Servers/Servers.test.tsx
src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap
src/domains/setting/pages/Servers/blocks/CustomPeers.tsx
src/domains/setting/pages/Servers/blocks/NodesStatus.tsx

https://app.clickup.com/t/8677d7w32

refactor: list musig servers separately

---

src/domains/wallet/components/WalletsGroup/WalletsGroup.test.tsx
src/domains/wallet/components/WalletsList/WalletsList.test.tsx
src/domains/wallet/pages/WalletGroupPage/WalletGroupPage.test.tsx

https://app.clickup.com/t/86774hntw

test: add musig mocks in wallet domain

---

src/app/contexts/Migration/Migration.test.tsx
src/app/contexts/Migration/Migration.tsx
src/domains/transaction/components/Migration/components/MigrationDetailsModal.test.tsx
src/domains/transaction/components/Migration/components/MigrationDetailsModal.tsx
src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
src/utils/polygon-migration.test.ts
src/utils/polygon-migration.ts

Removes the use of backslash in URLs in env. 
Closes https://app.clickup.com/t/8677ejj71

refactor: remove backslash from urls in env

---

src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.tsx
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRowMobile.test.tsx.snap
src/domains/vote/components/AddressTable/AddressTable.tsx
src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

Closes https://app.clickup.com/t/862jk1q3w

refactor: add links to vote page addresses

---

src/app/hooks/use-query-parameters.ts
src/app/hooks/use-search-parameters-validation.test.ts
src/domains/profile/hooks/use-profile-import.ts
src/domains/wallet/e2e/common.ts
src/domains/wallet/utils/get-default-alias.test.ts
src/tests/fixtures/transactions/index.ts
src/tests/mocks/networks.ts
src/utils/migrations/initialize-ark-networks.ts
src/utils/migrations/update-ark-nethashes.ts
src/utils/network-utils.ts

There is the possibility that changes here may break some tests but we need to fix the errors from https://github.com/ArdentHQ/arkvault/pull/410 to really know, for the moment we can focus manually ensuring that it works
Depends on https://github.com/ArdentHQ/platform-sdk/pulls
Related https://app.clickup.com/t/86dt3c4w3

refactor: adjust network configuration

---

src/domains/transaction/hooks/use-send-transfer-form.ts

Closes https://app.clickup.com/t/86dt3rxvy
Requires https://github.com/ArdentHQ/platform-sdk/pull/47

refactor: allow signing with signatory for non transfer txs

---

src/domains/transaction/hooks/use-send-transfer-form.ts

Depends https://github.com/ArdentHQ/platform-sdk/pull/53
Basically rollbacks the previous functionality since API is compatible with both ark/mainsail

refactor: use signature object for transfer

---

src/domains/setting/pages/Networks/Networks.tsx

Closes https://app.clickup.com/t/86dt60qr5

refactor: hide mainsail mainnnet

---

src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
src/domains/transaction/components/UsernameRegistrationDetail/UsernameRegistrationDetail.test.tsx
src/domains/transaction/components/UsernameRegistrationDetail/UsernameRegistrationDetail.tsx
src/domains/transaction/components/UsernameRegistrationDetail/index.ts
src/domains/transaction/components/UsernameResignationDetail/UsernameResignationDetail.test.tsx
src/domains/transaction/components/UsernameResignationDetail/UsernameResignationDetail.tsx
src/domains/transaction/components/UsernameResignationDetail/index.ts
src/domains/transaction/i18n.ts

https://app.clickup.com/t/86dt6bry9

refactor: handle username details modals

---

src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.test.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.tsx
src/utils/network-utils.test.ts
src/utils/network-utils.ts

Depends on https://github.com/ArdentHQ/platform-sdk/pull/69
Closes https://app.clickup.com/t/86dt844zf
fixup https://github.com/ArdentHQ/arkvault/pull/435
https://github.com/ArdentHQ/arkvault/assets/22020168/1489f0b6-ef52-476c-b62f-2162b279b53e

fix: improve ledger support checks on networks

---

src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx

https://app.clickup.com/t/86dt84dce

fix: missing translation for forging tooltip

---

src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx
src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx
src/domains/transaction/components/DelegateRegistrationForm/ReviewStep.tsx
src/domains/transaction/validations/ValidatorRegistration.ts

https://app.clickup.com/t/86drv5nfq

refactor: adjustments for validator registration and resignation

---

src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx
src/domains/transaction/components/UsernameRegistrationForm/FormStep.tsx
src/domains/vote/components/DelegateTable/DelegateRow/DelegateVoteButton.tsx
src/domains/vote/pages/Votes/Votes.tsx

adding cards for the ts-ignores that were added

fix: build errors

---

src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
src/domains/transaction/components/DelegateRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.tsx
src/domains/transaction/components/TransactionDetail/TransactionPublicKey/TransactionPublicKey.test.tsx
src/domains/transaction/components/TransactionDetail/TransactionPublicKey/TransactionPublicKey.tsx
src/domains/transaction/components/TransactionDetail/TransactionPublicKey/__snapshots__/TransactionPublicKey.test.tsx.snap
src/domains/transaction/components/TransactionDetail/TransactionPublicKey/index.ts

Closes  https://app.clickup.com/t/86dt8fyb7

feat: add `TransactionPublicKey` component

---

src/domains/transaction/components/UsernameRegistrationForm/FormStep.tsx
src/domains/transaction/validations/UsernameRegistration.ts
src/utils/debounce.ts

https://app.clickup.com/t/86dt8g7cf

fix: typing errors on username registration validation

---

src/app/App.tsx

https://app.clickup.com/t/86dt8fwv0

refactor: log stack trace on exceptions

---

src/app/hooks/use-validation.ts
src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx
src/domains/transaction/validations/DelegateRegistration.ts

closes https://app.clickup.com/t/86dt8g7cu

fix: refactor ignored delegate registration type issue

---

src/domains/transaction/components/InputFee/InputFee.tsx

Closes https://app.clickup.com/t/86dt88tnk 

fix: ensure advanced fee value is always defined

---

src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx

Closes https://app.clickup.com/t/86dt9150v 

refactor: use `TransactionPublicKey` component in tx success screen

---

src/app/hooks/use-validation.ts
src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx
src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
src/domains/transaction/components/FilterTransactions/FilterTransactions.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/PendingTransferRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/PendingTransferRowMobile.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRowMobile.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
src/domains/transaction/components/UsernameRegistrationDetail/UsernameRegistrationDetail.test.tsx
src/domains/transaction/components/UsernameRegistrationForm/UsernameRegistrationForm.tsx
src/domains/transaction/hooks/use-transaction-types.ts
src/domains/transaction/pages/SendDelegateResignation/ReviewStep.tsx
src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
src/domains/transaction/pages/SendUsernameResignation/SummaryStep.tsx
src/domains/transaction/validations/UsernameRegistration.ts
src/domains/transaction/validations/ValidatorRegistration.test.tsx
src/domains/vote/components/AddressTable/AddressTable.tsx
src/domains/vote/components/DelegateTable/DelegateFooter/DelegateFooter.tsx
src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
src/domains/vote/components/DelegateTable/DelegateTable.helpers.tsx
src/domains/vote/components/DelegateTable/DelegateTable.tsx
src/domains/vote/components/VotesHeader/VotesHeader.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx
src/domains/wallet/utils/selectDelegateValidatorTranslation.ts
src/utils/debounce.ts
src/utils/environment.ts
src/utils/network-utils.test.ts

fix: eslint automatic formatting

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx

Closes https://app.clickup.com/t/86dt9dyhf

refactor: always show send icon for multipayment

---

src/domains/transaction/components/TransactionExportModal/utils/transaction-exporter.factory.test.ts
src/domains/transaction/components/TransactionExportModal/utils/transaction-exporter.factory.ts

Closes: https://app.clickup.com/t/861n3nkch

refactor: use timestamp to paginate export query

---

src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
src/domains/wallet/i18n.ts

Closes https://app.clickup.com/t/86dtbn7kw
Had to add a new error message since the scenario that causes the issue doesnt was not handled

fix: handle ledger device not available bug

---

package.json
src/domains/transaction/pages/SendUsernameResignation/SendUsernameResignation.tsx

https://app.clickup.com/t/86dtbqbr0
Fixes the compilation bug and a logic bug related to some recent changes to the error page, onBack should return to the form step and onClose to the wallet details page

fix: username registration back compilation bug

---

.github/workflows/build.yml
.github/workflows/deps.yml
.github/workflows/e2e.yml
.github/workflows/format.yml
.github/workflows/test.yml
README.md
package.json
pnpm-lock.yaml
scripts/generate-test-workflow.js

Closes: https://app.clickup.com/t/86dtc0xum

chore: update Node to v20

---

.github/workflows/test.yml
src/domains/transaction/hooks/use-profile-transactions.test.tsx
src/domains/transaction/hooks/use-profile-transactions.ts
src/domains/transaction/hooks/use-transaction-types.test.tsx
src/domains/transaction/hooks/use-transaction-url.test.tsx

Closes https://app.clickup.com/t/86dtckh2n

chore: transactions hooks coverage

---

.github/workflows/test.yml
src/domains/transaction/validations/Authentication.test.tsx
src/domains/transaction/validations/Common.test.tsx
src/domains/transaction/validations/SendTransfer.test.tsx
src/domains/transaction/validations/SendVote.test.tsx

Close https://app.clickup.com/t/86dtckh39
Note is not 100% since `src/domains/transaction/validations/ValidatorRegistration.test.tsx` depends on mainsail network implementation

chore: transactions validations coverage

---

.github/workflows/test.yml
src/domains/message/pages/SignMessage/FormStep.tsx
src/domains/message/pages/SignMessage/SignMessage.test.tsx
src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SuccessStep.test.tsx.snap
src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap

Closes https://app.clickup.com/t/86dtfbtpu

chore: domains message test coverage

---

.github/workflows/test.yml
src/domains/wallet/utils/get-default-alias.test.ts

https://app.clickup.com/t/86dtckh6t

chore: domains wallets utils coverage

---

.github/workflows/test.yml
src/domains/wallet/hooks/use-wallet-actions.test.tsx
src/domains/wallet/hooks/use-wallet-config.test.tsx
src/domains/wallet/hooks/use-wallet-sync.test.tsx

Closes https://app.clickup.com/t/86dtfc1vy

chore: domains wallets hooks coverage

---

.github/workflows/test.yml
src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/WalletOverviewStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.test.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.tsx
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.WIF.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
src/domains/wallet/pages/WalletDetails/components/WalletHeaderMobile/__snapshots__/WalletHeaderMobile.test.tsx.snap
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.test.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
src/domains/wallet/pages/WalletDetails/hooks/use-wallet-options.test.tsx
src/domains/wallet/pages/WalletGroupPage/__snapshots__/WalletGroupPage.test.tsx.snap

https://app.clickup.com/t/86dtfc1z0

chore: domains wallets pages coverage

---

.github/workflows/test.yml
src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
src/domains/wallet/components/EncryptPasswordStep/EncryptPasswordStep.test.tsx
src/domains/wallet/components/EncryptPasswordStep/__snapshots__/EncryptPasswordStep.test.tsx.snap
src/domains/wallet/components/MnemonicList/MnemonicList.test.tsx
src/domains/wallet/components/MnemonicList/__snapshots__/MnemonicList.test.tsx.snap
src/domains/wallet/components/MnemonicVerification/MnemonicVerification.test.tsx
src/domains/wallet/components/MnemonicVerification/MnemonicVerificationInput.test.tsx
src/domains/wallet/components/NetworkStep/NetworkStep.test.tsx
src/domains/wallet/components/NetworkStep/NetworkStep.tsx
src/domains/wallet/components/NetworkStep/__snapshots__/NetworkStep.test.tsx.snap
src/domains/wallet/components/PortfolioHeader/__snapshots__/PortfolioHeader.test.tsx.snap
src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx
src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
src/domains/wallet/components/WalletActionsModals/__snapshots__/WalletActionsModals.test.tsx.snap
src/domains/wallet/components/WalletDetail/__snapshots__/WalletDetail.test.tsx.snap
src/domains/wallet/components/WalletDetailAddress/__snapshots__/WalletDetailAddress.test.tsx.snap
src/domains/wallet/components/WalletDetailNetwork/__snapshots__/WalletDetailNetwork.test.tsx.snap
src/domains/wallet/components/WalletsControls/WalletsControls.test.tsx
src/domains/wallet/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
src/domains/wallet/components/WalletsGroup/__snapshots__/WalletsGroup.test.tsx.snap
src/domains/wallet/components/WalletsGroup/__snapshots__/WalletsGroupHeader.test.tsx.snap
src/domains/wallet/components/WalletsGroup/__snapshots__/WalletsGroupsList.test.tsx.snap
src/domains/wallet/components/WalletsList/__snapshots__/WalletsList.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap

Closes https://app.clickup.com/t/86dtfc1u4

chore: domains wallets components coverage

---

.github/workflows/test.yml
src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRowMobile.test.tsx.snap
src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.test.tsx
src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
src/domains/vote/components/DelegateTable/DelegateRow/__snapshots__/DelegateRow.test.tsx.snap
src/domains/vote/components/DelegateTable/DelegateTable.test.tsx
src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap
src/domains/vote/components/VotesHeader/__snapshots__/VotesHeader.test.tsx.snap
src/domains/vote/pages/Votes/Votes.test.tsx
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

Closes https://app.clickup.com/t/86dtfvhv2

chore: domain vote coverage

---

src/domains/transaction/pages/SendRegistration/SendRegistration.test.tsx

Closes https://app.clickup.com/t/86dtj2yun

fix: send registration test

---

.github/workflows/build.yml

Missed this action on https://github.com/ArdentHQ/arkvault/pull/508

chore: use node 20 build action

---

src/domains/vote/components/DelegateTable/DelegateTable.test.tsx
src/domains/vote/components/DelegateTable/DelegateTable.tsx
src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap

Closes https://app.clickup.com/t/86dthrkm1

refactor: delegate pagination size per network adjustment

---

vite.config.ts

Closes https://app.clickup.com/t/86dt7z4qt

chore: optimize mainsail package 

---

src/domains/wallet/cucumber/create-wallet.ts
src/domains/wallet/cucumber/import-wallet.ts
src/domains/wallet/e2e/common.ts
src/utils/migrations/initialize-mainsail-networks.test.ts
src/utils/migrations/initialize-mainsail-networks.ts

Closes: https://app.clickup.com/t/86dtkz55r

test: enable E2E tests

---

src/utils/migrations/initialize-ark-networks.ts
src/utils/migrations/update-ark-constants.ts
src/utils/migrations/update-ark-nethashes.ts

Fixes  https://app.clickup.com/t/86dthqr1n for develop

refactor: prevent ark network from caching in migration

---

src/domains/transaction/cucumber/validator-registration.ts
src/domains/transaction/pages/SendRegistration/SendRegistration.test.tsx
src/domains/transaction/validations/ValidatorRegistration.test.tsx
src/domains/transaction/validations/ValidatorRegistration.ts

Closes: https://app.clickup.com/t/86dtgrepg

refactor: add public key validation

---

src/domains/transaction/components/TransactionExportModal/TransactionExportError/TransactionExportError.test.tsx
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.test.ts

chore: fix date ranges in transaction export test

---

src/domains/transaction/components/TransactionExportModal/TransactionExportError/TransactionExportError.test.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportError/TransactionExportError.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.contracts.ts
src/domains/transaction/components/TransactionExportModal/TransactionExportModal.tsx
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.test.ts
src/domains/transaction/components/TransactionExportModal/hooks/use-transaction-export.ts
src/domains/transaction/i18n.ts

Closes: https://app.clickup.com/t/861n3nkxb
https://github.com/ArdentHQ/arkvault/assets/132887516/f8b8490a-e687-4e4c-8e3f-8ca8a9f97075

refactor: make partial exports downloadable

---

src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.test.tsx
src/domains/transaction/components/TransactionSuccessful/hooks/useConfirmedTransaction.test.ts
src/domains/transaction/components/TransactionSuccessful/hooks/useConfirmedTransaction.ts
src/domains/transaction/cucumber/delegate-registration.ts
src/domains/transaction/cucumber/ipfs-transaction.ts
src/domains/transaction/cucumber/multiple-transfer.ts
src/domains/transaction/cucumber/single-transfer.ts
src/domains/transaction/cucumber/username-registration.ts
src/domains/transaction/cucumber/validator-registration.ts
src/domains/transaction/cucumber/vote-transaction.ts
src/domains/transaction/pages/SendRegistration/SendRegistration.test.tsx

Closes https://app.clickup.com/t/86dttf80f

fix: exit tx confirmation check interval on unmount

---

.npmrc

Closes https://app.clickup.com/t/86dtxav29

chore: ensure memory is enough when building project

---

src/domains/transaction/cucumber/username-registration.ts
src/domains/transaction/cucumber/username-resignation.ts
src/domains/transaction/cucumber/validator-registration.ts
src/domains/transaction/cucumber/validator-resignation.ts

Closes: https://app.clickup.com/t/86dtxr3ab

test: update transaction pool mocks

---

src/domains/transaction/components/AddRecipient/AddRecipient.tsx
src/domains/transaction/components/AddRecipient/AddRecipientItem.tsx
src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipientItem.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap

Additional fixes for https://app.clickup.com/t/86dtzgdag

chore: correct margins in multipay selection

---

src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
src/domains/vote/components/DelegateTable/DelegateRow/DelegateVoteAmount.test.tsx
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

chore: restore skipped tests

---

.github/workflows/test.yml
src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.test.tsx
src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap

Closes https://app.clickup.com/t/86du8z1t8

fix: restore & fix transaction domain tests

---

src/app/assets/svg/double-circle.svg
src/app/assets/svg/index.ts
src/app/i18n/common/i18n.ts
src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.blocks.test.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.blocks.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.test.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.tsx
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap

- New icon has been added.
- Translation file has been updated.
- New `LedgerWalletImport.blocks` file to store reusable components.
- Ledger import completed page has been refactored to match the new designs. This includes both the dark/light mode and desktop/mobile views.
- Single wallet import view has also been updated and refactored.
- Mobile light view:
- Desktop light view:
- Desktop dark view:
- Single wallet import desktop view:
- Single wallet import mobile view:
-   [ ] Ready to be …

refactor: completed import Ledger page

---

.github/workflows/test.yml
src/domains/exchange/pages/Exchange/Exchange.test.tsx

fix: restore full coverage in exchange domain

---

src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.blocks.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.blocks.tsx
src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap

- New reusable components `MobileCard` and `MobileSection` for rows have been implemented in the Ledger pages for scan and import.

refactor: implement mobile table reusable components

---

src/domains/transaction/pages/SendDelegateResignation/FormStep.tsx
src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap

Closes: https://app.clickup.com/t/86durvfcw
Design: https://www.figma.com/design/o6b1tEMOdUtHv7ijVs6pMX/ARKVault?node-id=13873-79174&node-type=frame&m=dev

refactor: delegate resignation create step adjustments

---

src/app/i18n/common/i18n.ts
src/domains/message/cucumber/sign-message.ts
src/domains/message/hooks/use-message-signer.test.tsx
src/domains/message/i18n.ts
src/domains/message/pages/SignMessage/FormStep.tsx
src/domains/message/pages/SignMessage/SignMessage.Encrypted.Mnemonic.test.tsx
src/domains/message/pages/SignMessage/SignMessage.Encrypted.Secret.test.tsx
src/domains/message/pages/SignMessage/SignMessage.test.tsx
src/domains/message/pages/SignMessage/SignMessage.tsx
src/domains/message/pages/SignMessage/SuccessStep.tsx
src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SuccessStep.test.tsx.snap

Closes https://app.clickup.com/t/86dutrah4 

refactor: UI adjustments on sign message flow

---

src/domains/wallet/pages/CreateWallet/SuccessStep.test.tsx
src/domains/wallet/pages/CreateWallet/SuccessStep.tsx
src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap

Closes https://app.clickup.com/t/86dutr9wn

refactor: adjust wallet creation success step UI

---

src/domains/message/pages/VerifyMessage/FormStep.tsx
src/domains/message/pages/VerifyMessage/SuccessStep.tsx
src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap

Closes https://app.clickup.com/t/86dutra55 

refactor: adjust UI on message verify flow

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.contracts.ts
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowSkeleton.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap

Closes https://app.clickup.com/t/86duvq4gu
https://github.com/user-attachments/assets/b735f810-7fb3-4bc3-a20e-b568d20d671a

fix: improve transaction table skeletons

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/PendingTransactionsTable.test.tsx
src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx

Closes https://app.clickup.com/t/86dutr4n7

fix: adjust size on pending tx from/to label

---

src/domains/dashboard/pages/Dashboard/Dashboard.tsx
src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap

Closes https://app.clickup.com/t/86dutreg4

refactor: adjust UI for dashboard tx table

---

src/app/components/Alert/Alert.tsx
src/app/components/Alert/__snapshots__/Alert.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap

Closes https://app.clickup.com/t/86dutr8y1

fix: correct chevron icon state

---

src/app/components/ListDivided/ListDividedItem.tsx
src/app/components/ListDivided/__snapshots__/ListDivided.test.tsx.snap
src/app/components/ListDivided/__snapshots__/ListDividedItem.test.tsx.snap
src/domains/setting/pages/Appearance/Appearance.tsx
src/domains/setting/pages/Appearance/__snapshots__/Appearance.test.tsx.snap
src/domains/setting/pages/Export/Export.tsx
src/domains/setting/pages/Export/__snapshots__/Export.test.tsx.snap
src/domains/setting/pages/General/General.tsx
src/domains/setting/pages/General/__snapshots__/General.test.tsx.snap
src/domains/setting/pages/Networks/Networks.tsx
src/domains/setting/pages/Networks/__snapshots__/Networks.test.tsx.snap
src/domains/setting/pages/Networks/blocks/CustomNetworksList.tsx
src/domains/setting/pages/Networks/blocks/NetworksList.tsx
src/domains/setting/pages/Password/Password.tsx
src/domains/setting/pages/Password/__snapshots__/Password.test.tsx.snap
src/domains/setting/pages/Servers/Servers.tsx
src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap

Closes https://app.clickup.com/t/86dutrbct

refactor: adjust spacing between settings components

---

src/app/components/Amount/AmountLabel.tsx
src/app/components/Amount/__snapshots__/AmountLabel.test.tsx.snap
src/domains/exchange/components/ExchangeTransactionsTable/ExchangeTransactionsRow.tsx
src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap
src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRow.test.tsx.snap
src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRowMobile.test.tsx.snap

Closes: https://app.clickup.com/t/86duwc8n2

fix: amount label height

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/PendingTransactionsTable.test.tsx
src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRowMobile.tsx

Closes https://app.clickup.com/t/86dutu6wa

fix: correct label size on mobile in pending transaction row

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx

Closes https://app.clickup.com/t/86duwbzk6 

fix: remove double tooltip in transaction row

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/PendingTransferRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRow.tsx

Closes https://app.clickup.com/t/86duttvcm

fix: improve alignment in pending transaction table

---

src/app/components/WalletListItem/WalletListItem.blocks.tsx
src/domains/transaction/components/SearchRecipient/SearchRecipient.tsx
src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap

Closes https://app.clickup.com/t/86duuft3a

fix: ui adjustments on recipients table

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx

Closes https://app.clickup.com/t/86dux5fv7

fix: correct transaction amount label based on transaction type

---

src/domains/transaction/components/AddRecipient/AddRecipientItem.tsx

Closes https://app.clickup.com/t/86dux5hrn

fix: correct multiple recipient label font sizes

---

src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap
src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap
src/domains/transaction/i18n.ts

Closes: https://app.clickup.com/t/86duwn81p

chore: replaced Second Signature with 2nd Signature

---

src/domains/transaction/components/VoteTransactionType/VoteTransactionType.tsx
src/domains/transaction/pages/SendVote/ReviewStep.tsx

Closes: https://app.clickup.com/t/86dux5hyw

fix: vote transaction review step alignment issue

---

src/domains/message/pages/SignMessage/SignMessage.tsx

Closes https://app.clickup.com/t/86dux5fz2

fix: correct button sizes in sign message form

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowMobile.test.tsx.snap
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap

Closes https://app.clickup.com/t/86dux5fxp

fix: correct alignment in wallet address in transaction table

---

src/app/components/Amount/AmountLabel.tsx
src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/SentStep.test.tsx.snap
src/domains/transaction/components/TransactionDetail/TransactionSummary/TransactionSummary.tsx
src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.Fees.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap

Closes https://app.clickup.com/t/86dux5fwt

fix: correct amount label font size in transaction details

---

src/domains/wallet/components/SearchWallet/SearchWallet.tsx
src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap

Closes https://app.clickup.com/t/86dux5fnk

fix: correct alignment & font  sizes in search wallet table

---

src/domains/transaction/components/SearchRecipient/SearchRecipient.tsx
src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap

Closes https://app.clickup.com/t/86dux5fr6

fix: correct alignment & font  sizes in recipient search modal

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx

Closes https://app.clickup.com/t/86dux5gtz

fix: correct sender address color for incoming transactions

---

src/app/components/ControlButton/ControlButton.tsx

Closes https://app.clickup.com/t/86dux5rjm

fix: correct color on dashboard filter icon

---

src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.blocks.tsx

Closes https://app.clickup.com/t/86dux5jar

fix: consistently align wallet header items

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap

Closes: https://app.clickup.com/t/86dux6k17

fix: transfer transaction addressing

---

src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx

Closes: https://app.clickup.com/t/86dux5k3j

fix: add icon for the authentication step

---

src/app/components/WalletListItem/WalletListItem.blocks.tsx

Closes https://app.clickup.com/t/86dux5tnc

fix: correct colors for disabled send button in wallet list on mobile

---

src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionAddresses.tsx
src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionRecipient.tsx

Closes https://app.clickup.com/t/86dux5grb

fix: correct colors for recipient address in transaction detail

---

src/app/components/NavigationBar/NavigationBar.blocks.tsx
src/app/components/PageSkeleton/ProfilePageSkeleton.tsx
src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.blocks.tsx

Closes https://app.clickup.com/t/86dux5ux3

fix: adjust height on mobile navigation bar

---

src/app/components/Input/Input.tsx

Closes https://app.clickup.com/t/86dux79wt

fix: correct placeholder color in inputs

---

src/app/components/SelectDropdown/styles.ts

Closes https://app.clickup.com/t/86dux65cy

refactor: adjust paddings in mobile select dropdown

---

src/app/components/SelectDropdown/SelectDropdown.tsx

Closes https://app.clickup.com/t/86dux62ju

refactor: adjust select caret icon

---

src/domains/transaction/components/DelegateRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/MultiSignatureRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/SecondSignatureRegistrationForm/ReviewStep.tsx
src/domains/transaction/pages/SendDelegateResignation/ReviewStep.tsx
src/domains/transaction/pages/SendTransfer/ReviewStep.tsx
src/domains/transaction/pages/SendVote/ReviewStep.tsx
src/domains/wallet/pages/CreateWallet/ConfirmPassphraseStep.tsx

Closes https://app.clickup.com/t/86dux66zd

fix: adjust transaction review step alignment 

---

src/domains/profile/components/SelectRecipient/SelectRecipient.tsx

Closes https://app.clickup.com/t/86dux65mk

fix: use truncation on recipient dropdown list

---

src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/SentStep.test.tsx.snap
src/domains/transaction/components/TransactionDetail/TransactionType/TransactionType.test.tsx
src/domains/transaction/pages/SendIpfs/SendIpfs.Encryption.test.tsx
src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.Encryption.test.tsx.snap
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.Fees.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap

Restores failing tests for ipfs pages after recent refactor

test: restore failing tests & coverage

---

src/domains/transaction/components/TransactionDetail/TransactionSummary/TransactionSummary.tsx

Fixes https://app.clickup.com/t/86dux5fwt

fix: correct amount label font size in transaction summary

---

src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
src/domains/wallet/components/WalletsList/WalletsList.tsx

Closes: https://app.clickup.com/t/86duxvpf4

fix: adjust font size of wallets pagination select

---

src/domains/transaction/pages/SendVote/ReviewStep.tsx

Closes https://app.clickup.com/t/86duyugj8 

fix: correct padding in vote review page

---

src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.tsx

Closes https://app.clickup.com/t/86duu4f85 

fix: show ledger import title in sm screens

---

src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
src/domains/transaction/components/VoteTransactionType/helpers.ts
src/domains/transaction/hooks/use-transaction-voting-wallets.ts

Closes https://app.clickup.com/t/86dux5j0y

fix: display delegate information in summary step for vote txs

---

src/domains/transaction/pages/SendTransfer/FormStep.tsx
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap

Closes https://app.clickup.com/t/86duy4ph4 

fix: adjust scan qr button UI on mobile 

---

src/domains/wallet/pages/WalletDetails/components/WalletHeaderMobile/WalletHeaderMobile.tsx
src/domains/wallet/pages/WalletDetails/components/WalletHeaderMobile/__snapshots__/WalletHeaderMobile.test.tsx.snap

Closes https://app.clickup.com/t/86dux5u8t

fix: use available space for  wallet details address in mobile

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx

Closes https://app.clickup.com/t/86duyvaf7 
Preview:

fix: improve send details in pending musig transactions

---

src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx
src/domains/transaction/components/DelegateRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap

Closes: https://app.clickup.com/t/86duzmpdb

refactor: adjust delegate registration form step

---

src/domains/profile/components/SelectRecipient/SelectRecipient.tsx

Closes https://app.clickup.com/t/86duzmzk5 

refactor: reduce font size in recipient dropdown on mobile

---

src/app/components/PageSkeleton/__snapshots__/PageSkeleton.test.tsx.snap
src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap

chore: update snapshots

---

src/domains/transaction/components/DelegateRegistrationForm/ReviewStep.tsx

Closes: https://app.clickup.com/t/86duzp142

fix: align register delegate review step

---

src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.tsx

Closes https://app.clickup.com/t/86duuzc6k 

refactor: add ledger support in exchange transaction flow

---

src/app/components/DetailWrapper/DetailWrapper.tsx
src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SuccessStep.test.tsx.snap
src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
src/domains/transaction/components/MultiSignatureDetail/__snapshots__/SentStep.test.tsx.snap
src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionRecipient.tsx
src/domains/transaction/components/TransactionDetail/TransactionDetails/TransactionDetails.tsx
src/domains/transaction/components/TransactionDetail/TransactionId/TransactionId.tsx
src/domains/transaction/components/TransactionDetail/TransactionSummary/TransactionSummary.tsx
src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.Encryption.test.tsx.snap
src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/LedgerReview.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.Fees.test.tsx.snap
src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap

Closes: https://app.clickup.com/t/86dv01ghr

fix: adjust text size for transaction details

---

src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
src/domains/wallet/i18n.ts
src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.blocks.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.tsx

Closes https://app.clickup.com/t/86duu4enr 

refactor: adjust ledger loading screen

---

src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.Ledger.test.tsx
src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.test.tsx
src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.tsx

Closes https://app.clickup.com/t/86dv0c55u 

test: restore coverage in exchange domain

---

src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
src/domains/transaction/components/VoteTransactionType/helpers.ts

Closes: https://app.clickup.com/t/86dv0xymm

fix: signed vote swap tx details

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap

Closes: https://app.clickup.com/t/86dv1fu9e

fix: multipayment transaction amount

---

src/domains/transaction/components/Transactions/Transactions.tsx
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap
src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transaction-counts.test.tsx
src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transaction-counts.tsx

Closes https://app.clickup.com/t/86dum089v 
Add total counts for incoming & outgoing transactions in the respective tabs.

feat: add wallet transactions total count in wallet tabs

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionAmount.blocks.tsx

Closes: https://app.clickup.com/t/86dv45qqz
**Multipayment tx: A is sender, A and B are receivers**
A POV: `DErsBi7QDiqxj6jh5C5VgK3qaksQbkG6F9`, Received 1 DARK
B POV: `DKM6QNS5bLggQmUbtpXiARCgjvwhXGNq4Z`, Received 0.5 DARK
------------------------
**Multipayment tx: A is sender, B and C are receivers**
A POV: `DErsBi7QDiqxj6jh5C5VgK3qaksQbkG6F9`
B POV: `DKM6QNS5bLggQmUbtpXiARCgjvwhXGNq4Z` Received 0.1 DARK
C POV: `DG251q3GRUzTsS6FGrx5tZrEhG8C4iVWVS` Received 0.1 DARK
------------------
**Multipayment tx: A is sender, A and A are receivers**
A POV: `DErsBi7QDiqxj6jh5C5VgK3qaksQbkG6F9`
-------
**Single transfer tx: A is sender, A is receiver**
-----
**Single transfer tx: A is sender, B is receiver**
A POV: `DErsBi7QDiqxj6jh5C5VgK3qaksQbkG6F9`
B POV: `DKM6QNS5bLggQmUbtpXiARCgjvwhXGNq4Z`, …

fix: sent to self label

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap

Closes: https://app.clickup.com/t/86dv4f4qr
**from**:
scan:
vault:
**to**:
scan:
vault:

fix: multipayment tx addressing

---

src/app/components/PageSkeleton/__snapshots__/PageSkeleton.test.tsx.snap
src/domains/profile/components/ProfileRow/ProfileRow.tsx
src/domains/profile/components/ProfileRow/__snapshots__/ProfileRow.test.tsx.snap

Closes https://app.clickup.com/t/86dv94y63

fix: correct colors for profile row skeleton in welcome page

---

package.json
src/app/components/PageSkeleton/__snapshots__/PageSkeleton.test.tsx.snap
src/domains/profile/components/ProfileRow/ProfileRow.tsx
src/domains/profile/components/ProfileRow/__snapshots__/ProfileRow.test.tsx.snap
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/BasicSettings.tsx
src/domains/transaction/components/TransactionExportModal/TransactionExportForm/CsvSettings.tsx

chore: merge rc into main

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx

Closes https://app.clickup.com/t/86dvabpvb

fix: properly display contract label in transaction rows

---

src/domains/vote/components/ValidatorsTable/__snapshots__/ValidatorsTable.test.tsx.snap
src/domains/vote/i18n.ts
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

Closes: https://app.clickup.com/t/86dvchet3

chore: adjust validator name column

---

src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.test.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap

Closes https://app.clickup.com/t/86dvbvrx3

fix: show validator address at wallet voting section

---

src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

Closes https://app.clickup.com/t/86dvn5aq2 

fix: prevent early submission in the send transfer form

---

src/app/components/Label/Label.tsx
src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
src/app/components/NavigationBar/NavigationBar.blocks.tsx
src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
src/app/components/Table/TableRow.tsx
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.blocks.tsx
src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
src/domains/wallet/pages/WalletGroupPage/__snapshots__/WalletGroupPage.test.tsx.snap

Closes https://app.clickup.com/t/86dvn5c4t 

chore: fix console dev errors

---

src/domains/dashboard/pages/Dashboard/Dashboard.tsx
src/domains/transaction/components/TransactionTable/TransactionTable.contracts.tsx
src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
src/domains/transaction/components/TransactionTable/TransactionTable.tsx
src/domains/transaction/components/Transactions/Transactions.tsx
src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.Keyboard.test.tsx

Closes https://app.clickup.com/t/86dvpwqgj 

fix: provide coin name when available in tx table

---

src/app/components/StepNavigation/StepNavigation.tsx
src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

fix: restore tx sending

---

src/domains/dashboard/pages/Dashboard/Dashboard.Empty.blocks.tsx
src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx
src/domains/wallet/pages/WalletDetails/components/AddressesSidePanel/AddressesSidePanel.test.tsx
src/domains/wallet/pages/WalletDetails/components/AddressesSidePanel/AddressesSidePanel.tsx
src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx

Closes https://app.clickup.com/t/86dvn1683

refactor: update selected addresses when closing side panel

---

src/domains/transaction/hooks/use-send-transfer-form.ts
src/domains/transaction/pages/SendTransfer/FormStep.tsx
src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

Closes https://app.clickup.com/t/86dvvn1jr 

fix: improve sender address handling in sender transfer form

---

src/domains/transaction/hooks/use-profile-transactions.ts

Closes https://app.clickup.com/t/86dvx2y9f

fix: sync portfolio txs when switching wallets with same selection size

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx

Fixes https://app.clickup.com/t/86dvvnq9x?comment=90170093745112

fix: correct width for larger screens on tx row addresses

---

src/domains/transaction/components/ValidatorRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/ValidatorRegistrationForm/ValidatorRegistrationForm.tsx
src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
src/domains/transaction/pages/SendValidatorResignation/ReviewStep.tsx
src/domains/transaction/pages/SendValidatorResignation/SendValidatorResignation.tsx
src/domains/transaction/pages/SendVote/ReviewStep.tsx
src/domains/transaction/pages/SendVote/SendVote.tsx

Closes: https://app.clickup.com/t/86dvwmm3f
This PR fixes sending vote and validator transactions.
**Validator registration/resignation txs:**
[Screencast from 2025-02-06 20-38-43.webm](https://github.com/user-attachments/assets/d8031050-ccff-4b3c-b694-1e4fe392f446)
**Vote txs:**
[Screencast from 2025-02-06 20-39-55.webm](https://github.com/user-attachments/assets/bfb18396-757f-40ea-883d-0810eee35519)

fix: vote and validator transaction sending

---

src/domains/transaction/pages/SendTransfer/FormStep.tsx
src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

Closes https://app.clickup.com/t/86dvzpfh4 

fix: remove network step from send transfer form

---

src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionRecipient.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx

Closes https://app.clickup.com/t/86dvyzmub 

fix: remove wrap from method column

---

src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMobile.test.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMobile.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowMobile.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx

- `Value` column has been renamed to simply `Amount` and the logic behind toggling this title name has been removed.
- Mobile transaction row has also been refactored to support this change.
- Unit tests have been refactored to support these changes.

refactor: transaction amount column rename

---

.gitignore

```plaintext
useful for adding specific settings for those of us who use vscode
```

chore: ignore .vscode settings folder

---

src/domains/transaction/components/UsernameRegistrationForm/FormStep.tsx
src/domains/transaction/components/ValidatorRegistrationForm/FormStep.tsx
src/domains/transaction/pages/SendTransfer/FormStep.tsx
src/domains/transaction/pages/SendUsernameResignation/FormStep.tsx
src/domains/transaction/pages/SendValidatorResignation/FormStep.tsx

Closes https://app.clickup.com/t/86dw0mz0a 

fix: remove duplicate addresses on sender modals

---

src/app/components/Address/Address.tsx

https://app.clickup.com/t/86dvx90jw

fix: adjust truncation when alias changes

---

src/domains/transaction/i18n.ts

- The tooltip for multiple recipients transactions has been reworded.

refactor: reword multiple recipients tooltip

---

src/app/components/SidePanel/SidePanel.tsx

https://app.clickup.com/t/86dw00kgk

feat: make side panel ignore outside clicks on toasts

---

src/app/hooks/use-wallet-alias.test.tsx
src/app/hooks/use-wallet-alias.tsx
src/tests/mocks/handlers/devnet.ts

Closes: https://app.clickup.com/t/86dw28vhh
This PR updates alias handling to consider known wallets.

refactor: handle known wallets for alias

---

src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
src/app/components/NavigationBar/NavigationBar.blocks.tsx
src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
src/app/components/PageSkeleton/__snapshots__/PageSkeleton.test.tsx.snap
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
src/domains/dashboard/pages/Dashboard/Dashboard.Empty.tsx
src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap
src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

Closes https://app.clickup.com/t/86dw4vjd6 

fix: correct logo UI in welcome page

---

src/app/contexts/Ledger/ledger.transport.factory.ts
src/utils/ledger-test-helpers.ts

fix: temporarily disable ledger dependencies

---

src/domains/transaction/pages/SendTransfer/FormStep.tsx

Potential fix for https://app.clickup.com/t/86dw4vjxg

fix: prevent multiple rerenders in transfer form

---

src/app/components/SidePanel/SidePanel.tsx
src/domains/portfolio/components/AddressesSidePanel/MobileAddressRow.tsx

Closes: https://app.clickup.com/t/86dw5xe02
- Fixes side panel width issue
- Fixes address truncation in mobile screen
[Screencast from 2025-03-07 19-02-09.webm](https://github.com/user-attachments/assets/593bbe9e-22dc-44fc-b940-f5f557cbe941)

refactor: fix side panel width

---

src/domains/portfolio/components/AddressesSidePanel/AddressesSidePanel.tsx
src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx

Closes: https://app.clickup.com/t/86dw5xa92 & https://app.clickup.com/t/86dw3g6da
This PR fixes selected addresses in the side panel after import & create
[Screencast from 2025-03-07 19-34-19.webm](https://github.com/user-attachments/assets/1563c714-2679-4a05-9038-b85b387ef1d8)

fix: selected addresses in side panel

---

src/domains/dashboard/pages/Dashboard/Dashboard.tsx

Closes: https://app.clickup.com/t/86dw57ywr
[Screencast from 2025-03-11 15-42-30.webm](https://github.com/user-attachments/assets/749d151a-977d-4b74-b2c9-151bdc4764e2)

fix: vote block showing wrong validator

---

src/domains/portfolio/components/AddressesSidePanel/AddressesSidePanel.tsx

Closes: https://app.clickup.com/t/86dw7nqfp
https://github.com/user-attachments/assets/63148194-fdce-4124-adfe-e1d64bee1356

fix: addresses side panel focus

---

src/app/components/DetailWrapper/DetailWrapper.tsx
src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SuccessStep.test.tsx.snap
src/domains/transaction/pages/SendVote/FormStep.tsx

- Border color in dark mode for the vote form has been aligned.
- Border radius for the sender has been adjusted to match the section below.

fix: vote form UI issues

---

src/app/hooks/use-networks.test.tsx
src/domains/contact/components/ContactForm/ContactForm.test.tsx
src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
src/domains/contact/components/ContactListItemMobile/ContactListItemMobile.test.tsx
src/domains/contact/components/ContactListItemMobile/__snapshots__/ContactListItemMobile.test.tsx.snap
src/domains/contact/components/CreateContact/CreateContact.test.tsx
src/domains/contact/components/DeleteContact/DeleteContact.test.tsx
src/domains/contact/components/UpdateContact/UpdateContact.test.tsx
src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
src/domains/contact/pages/Contacts/Contacts.test.tsx
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
src/tests/fixtures/env/storage.json
src/utils/test-helpers.ts
src/utils/testing-library.tsx

As a part of: https://app.clickup.com/t/86dw4wc2b
This PR updates `contact` domain tests to use `Mainsail` network so we can get rid of `Ark` network.

tests: update `contact` domain tests to use `Mainsail` network

---

src/domains/portfolio/components/ImportWallet/ImportAddressSidePanel.tsx

Closes: https://app.clickup.com/t/86dw9x6n1
[Screencast from 2025-03-19 23-57-18.webm](https://github.com/user-attachments/assets/5f732118-27eb-4dae-a038-b130868768fc)

fix: avoid enabled `Continue` button with invalid form state

---

src/app/App.blocks.tsx
src/app/components/NavigationBar/components/HideBalance/HideBalance.tsx
src/app/components/NavigationBar/components/UserMenu/UserMenu.tsx
src/app/components/ServerStatusIndicator/ServerStatusIndicator.test.tsx
src/app/components/WalletListItem/WalletListItem.blocks.test.tsx
src/app/components/WalletListItem/WalletListItem.blocks.tsx
src/app/contexts/Configuration/Configuration.test.tsx
src/app/contexts/Configuration/Configuration.tsx
src/app/hooks/use-profile-synchronizer.resync.test.tsx
src/app/hooks/use-profile-synchronizer.test.tsx
src/app/hooks/use-profile-synchronizer.ts
src/app/hooks/use-server-health-status.test.tsx
src/app/hooks/use-server-health-status.ts
src/domains/dashboard/pages/Dashboard/Dashboard.tsx
src/domains/profile/hooks/use-welcome-modal.ts
src/domains/setting/pages/Servers/blocks/NodesStatus.tsx
src/domains/setting/pages/Servers/hooks/use-server-status.ts
src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.tsx
src/domains/vote/components/AddressTable/AddressTable.test.tsx
src/domains/vote/pages/Votes/Votes.test.tsx
src/domains/wallet/components/WalletsList/WalletsList.tsx
src/domains/wallet/hooks/use-wallet-config.ts

Modifies the `use-profile-synchronizer` hook to handle status by profile. This is a breaking change, so I recommend comprehensive testing
https://app.clickup.com/t/86dw8yz70

fix: switching profiles bug

---

src/domains/wallet/i18n.ts

- Subtitles for the import sidebar have been updated.
- Title has also been fixed (it was previously displaying "Import Ledger".

refactor: adjust import subtitles

---

src/domains/transaction/components/TransactionTable/TransactionTable.tsx

https://app.clickup.com/t/86dwb989t

fix: switching addresses count breaks transaction table

---

src/domains/portfolio/components/AddressesSidePanel/AddressRow.tsx

https://app.clickup.com/t/86dwc77gt

refactor: dont show hover side panel when deleting

---

src/domains/portfolio/components/AddressesSidePanel/AddressesSidePanel.tsx

https://app.clickup.com/t/86dwc6n7k

refactor: handle deleted wallet on address panel single view

---

.github/workflows/build.yml
.github/workflows/deps.yml
.github/workflows/e2e.yml
.github/workflows/format.yml
.github/workflows/snapshots.yml
.github/workflows/test.yml

updates CI to run on `pnpm 10`

chore: update workflows to pnpm 10

---

src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

- Navbar was previously being contained in a div with margin. Now, it has been moved out from that part of the code, allowing it to cover the whole page.

fix: scan modal issue

---

src/app/components/Address/Address.tsx
src/app/components/NavigationBar/NavigationBar.test.tsx
src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
src/domains/contact/components/ContactListItemMobile/__snapshots__/ContactListItemMobile.test.tsx.snap
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
src/domains/message/pages/SignMessage/__snapshots__/SuccessStep.test.tsx.snap
src/domains/portfolio/components/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap

Closes: https://app.clickup.com/t/86dw6r3yy
Source: https://helloardent.slack.com/archives/C03889W1KHT/p1744027049276299?thread_ts=1741866803.718849&cid=C03889W1KHT
Light mode:
Color: `gray-700` 
Hover Color: `primary-700`
Dark mode:
Color: `dark-200`
Hover Color: `dark-50`

refactor: adjust copy to clipboard icon color

---

src/domains/transaction/components/UsernameRegistrationForm/UsernameRegistrationForm.tsx
src/domains/transaction/components/ValidatorRegistrationForm/ValidatorRegistrationForm.tsx
src/domains/transaction/hooks/use-multisignature-registration.ts
src/domains/transaction/hooks/use-send-transfer-form.ts
src/domains/transaction/hooks/use-transaction-builder.ts
src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
src/domains/transaction/pages/SendUsernameResignation/SendUsernameResignation.tsx
src/domains/transaction/pages/SendValidatorResignation/SendValidatorResignation.tsx
src/domains/transaction/pages/SendVote/SendVote.tsx

https://app.clickup.com/t/86dwf92ba

fix: nonce issue when voting

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx

https://app.clickup.com/t/86dwfh84u

fix: ensure recipient does not wrap for contracts

---

src/domains/contact/i18n.ts
src/domains/contact/pages/Contacts/__snapshots__/Contacts.blocks.test.tsx.snap
src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap

Adds the missing period on contact section
https://app.clickup.com/t/86dwfjh9p

chore: add missing periods

---

src/app/hooks/use-validation.test.tsx
src/domains/transaction/validations/UsernameRegistration.ts

Closes: https://app.clickup.com/t/86dwgnktf
[Screencast from 2025-04-14 14-51-42.webm](https://github.com/user-attachments/assets/5947e644-a796-4ca0-8967-688a43a32737)

refactor: improve username validation

---

src/app/lib/mainsail/confirmed-transaction.dto.ts
src/app/lib/mainsail/signed-transaction.dto.ts
src/domains/transaction/validations/Common.ts

Closes: https://app.clickup.com/t/86dwgnk5x
[Screencast from 2025-04-15 15-44-03.webm](https://github.com/user-attachments/assets/f46daa4a-565f-4ef8-9dd3-ba5a25bd9181)

fix: transaction details

---

src/app/lib/mainsail/confirmed-transaction.dto.ts
src/app/lib/mainsail/crypto/enums.ts
src/app/lib/mainsail/fee.service.ts
src/app/lib/mainsail/signed-transaction.dto.ts
src/app/lib/sdk/confirmed-transaction.dto.contract.ts
src/app/lib/sdk/confirmed-transaction.dto.ts
src/app/lib/sdk/fee.contract.ts
src/app/lib/sdk/signed-transaction.dto.contract.ts
src/app/lib/sdk/signed-transaction.dto.ts
src/domains/transaction/components/FeeField/FeeField.tsx
src/domains/transaction/components/ValidatorRegistrationForm/ReviewStep.tsx
src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
src/domains/transaction/pages/SendValidatorResignation/ReviewStep.tsx
src/domains/transaction/pages/SendValidatorResignation/SendValidatorResignation.tsx
src/domains/transaction/utils.ts

Closes: https://app.clickup.com/t/86dwgnwaa

refactor: adjust DTOs to match Mainsail

---

src/domains/portfolio/components/ImportWallet/ImportDetailStep.tsx
src/domains/wallet/components/WalletEncryptionBanner.tsx/WalletEncryptionBanner.tsx

Closes: https://app.clickup.com/t/86dwh49d7
[Screencast from 2025-04-16 16-11-02.webm](https://github.com/user-attachments/assets/9a9d2c3a-16f3-4c79-986c-76cebcb5ca2c)

fix: import address encryption tooltip

---

package.json
pnpm-lock.yaml
src/app/lib/markets/contracts/historical.ts
src/app/lib/markets/contracts/index.ts
src/app/lib/markets/contracts/market.ts
src/app/lib/markets/contracts/tracker.ts
src/app/lib/markets/drivers/coincap/index.ts
src/app/lib/markets/drivers/coincap/transformers/historical-price-transformer.ts
src/app/lib/markets/drivers/coincap/transformers/market-transformer.ts
src/app/lib/markets/drivers/coincap/utils.ts
src/app/lib/markets/drivers/coingecko/index.ts
src/app/lib/markets/drivers/coingecko/transformers/historical-price-transformer.ts
src/app/lib/markets/drivers/coingecko/transformers/historical-volume-transformer.ts
src/app/lib/markets/drivers/coingecko/transformers/market-transformer.ts
src/app/lib/markets/drivers/cryptocompare/index.ts
src/app/lib/markets/drivers/cryptocompare/transformers/historical-price-transformer.ts
src/app/lib/markets/drivers/cryptocompare/transformers/historical-volume-transformer.ts
src/app/lib/markets/drivers/cryptocompare/transformers/market-transformer.ts
src/app/lib/markets/index.ts
src/app/lib/profiles/exchange-rate.service.ts

Closes https://app.clickup.com/t/86dwk384n

refactor: move `@ardenthq/sdk-markets` internally

---

package.json
pnpm-lock.yaml
src/app/lib/mainsail/public-key.service.ts
src/app/lib/sdk/extended-public-key.contract.ts
src/app/lib/sdk/extended-public-key.service.ts
src/app/lib/sdk/public-key.contract.ts
src/app/lib/sdk/public-key.service.ts
src/domains/transaction/validations/ValidatorRegistration.ts

Closes: https://app.clickup.com/t/86dwkt302
This PR enables BLS key validation. For testing send a validator tx.

refactor: enable BLS key validation

---

.github/workflows/test.yml

As a part of https://app.clickup.com/t/86dwhq2pp

chore: disable tests in CI per domain

---

src/app/lib/mainsail/address.service.ts
src/app/lib/mainsail/private-key.service.ts
src/app/lib/mainsail/public-key.service.ts

This PR restores `bip39` checks to improve UX. 
Closes:
- https://app.clickup.com/t/86dwhc1jr
- https://app.clickup.com/t/86dwqjbkv

refactor: restore `bip39` checks

---

src/app/components/Clipboard/ClipboardIcon.tsx

Closes: https://app.clickup.com/t/86dwrbh8u
[Screencast from 2025-05-19 13-07-19.webm](https://github.com/user-attachments/assets/7e47b3cc-9f2c-49d2-b2a5-7ace808c99d4)

refactor: stop event bubbling for copy icon

---

src/domains/transaction/components/FeeField/FeeField.tsx

Closes: https://app.clickup.com/t/86dwy4j54
Serialized `data` to prevent infinite loop.

fix: infinite rendering issue in vote tx page

---

.github/workflows/test.yml
src/utils/assertions.test.ts
src/utils/delay.test.ts
src/utils/environment.test.ts
src/utils/network-utils.test.ts
src/utils/peers.test.ts
src/utils/peers.ts
src/utils/platform.test.ts
src/utils/profile-peers.test.ts
src/utils/profile-peers.ts
src/utils/server-utils.test.ts
src/utils/server-utils.ts
src/utils/theme.test.ts
vitest.config.ts

https://app.clickup.com/t/86dwyebnv

test: increase utils coverage

---

.github/workflows/test.yml
src/domains/transaction/validations/Authentication.test.tsx
src/domains/transaction/validations/Common.test.tsx
src/domains/transaction/validations/DelegateRegistration.test.ts
src/domains/transaction/validations/SendTransfer.test.tsx
src/domains/transaction/validations/SendVote.test.tsx
src/domains/transaction/validations/UsernameRegistration.test.ts
src/domains/transaction/validations/UsernameRegistration.ts
src/domains/transaction/validations/ValidatorRegistration.test.tsx
src/utils/testing-library.tsx

https://app.clickup.com/t/86dwz6vqe

test: increase test coverage for validations

---

.github/workflows/test.yml
src/domains/transaction/hooks/use-profile-transactions.test.tsx
src/domains/transaction/hooks/use-profile-transactions.ts
src/domains/transaction/hooks/use-transaction-types.test.tsx
src/domains/transaction/hooks/use-transaction-url.test.tsx

https://app.clickup.com/t/86dwzt0hq

test: increase transaction hooks coverage

---

src/app/lib/profiles/helpers/attribute-bag.test.ts
src/app/lib/profiles/helpers/avatar.test.ts
src/app/lib/profiles/helpers/currency.test.ts
src/app/lib/profiles/helpers/queue.test.ts

https://app.clickup.com/t/86dx0e0we

test: lib profiles helpers coverage

---

eslint.config.mjs

https://app.clickup.com/t/86dx1kytg
Also the rule "@typescript-eslint/no-unused-expressions" creates an exception as it is

chore: fix eslint configuration

---

src/app/lib/helpers/clone-deep.test.ts
src/app/lib/helpers/qrcode.test.ts
src/app/lib/helpers/set.test.ts
src/app/lib/mainsail/helpers/hosts.test.ts
src/app/lib/markets/index.ts

This PR adds types for a few files - I couldn't suppress these in arkconnect, that is why decided to add here to keep changes in sync

chore: improve types

---

src/app/lib/profiles/validator-syncer.service.ts
src/app/lib/profiles/validator.service.ts

Closes https://app.clickup.com/t/86dx23ccw 

refactor: improve sync time & cache validators

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap

Closes https://app.clickup.com/t/86dx3gbwr 

fix: center align rank in wallet vote info

---

src/app/lib/mainsail/wallet.dto.ts

https://app.clickup.com/t/86dx1vzhd and https://app.clickup.com/t/86dx3g8nu

refactor: hide validator registration if already registered

---

src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
src/domains/vote/components/AddressTable/AddressTable.tsx
src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap

Closes https://app.clickup.com/t/86dx457j1 

fix: correct alignment in validators table

---

src/domains/transaction/hooks/use-transaction-types.test.tsx
src/domains/transaction/hooks/use-transaction-types.ts

https://app.clickup.com/t/86dx58r7z

refactor: return method signature if unknown method

---

src/domains/transaction/hooks/use-profile-transactions.ts

https://app.clickup.com/t/86dx5jbz7

fix: load more transactions does not persist

---

src/app/i18n/common/i18n.ts
src/domains/transaction/components/UsernameRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/ValidatorRegistrationForm/ReviewStep.tsx
src/domains/transaction/components/ValidatorRegistrationForm/__snapshots__/ValidatorRegistrationForm.test.tsx.snap
src/domains/transaction/pages/SendUsernameResignation/FormStep.tsx
src/domains/transaction/pages/SendUsernameResignation/ReviewStep.tsx
src/domains/transaction/pages/SendValidatorResignation/FormStep.tsx
src/domains/transaction/pages/SendValidatorResignation/ReviewStep.tsx
src/domains/transaction/pages/SendValidatorResignation/__snapshots__/SendValidatorResignation.test.tsx.snap

Closes https://app.clickup.com/t/86dx5jcxm

fix: use `Method` label instead of `Category` in tx flow pages

---

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowId.tsx
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap

Closes https://app.clickup.com/t/86dx5jd81 

fix: truncate failed label in tx table in mobile

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx

Closes https://app.clickup.com/t/86dx5jbnu 

fix: use available space for porftolio header address

---

.github/workflows/e2e.yml
src/domains/transaction/components/InputFee/blocks/InputFeeSimple.tsx

As a part of: https://app.clickup.com/t/86dwz4k7b

test: disable e2e test workflows

---

src/app/lib/mainsail/transaction.service.ts

Closes https://app.clickup.com/t/86dwygnkh

fix: ensure ledger is connected when signing transactions

---

.github/workflows/test.yml
src/app/lib/profiles/transaction-index.test.ts
src/app/lib/profiles/transaction.aggregate.test.ts
src/app/lib/profiles/transaction.aggregate.ts
src/app/lib/profiles/transaction.collection.test.ts
src/app/lib/profiles/transaction.collection.ts
src/app/lib/profiles/transaction.dto.test.ts
src/app/lib/profiles/transaction.mapper.test.ts

https://app.clickup.com/t/86dx7wfg2

test: lib profile transaction coverage

---

src/domains/setting/pages/Password/__snapshots__/Password.test.tsx.snap

test: fix failing snapshots in settings tests

---

src/domains/profile/pages/Welcome/Welcome.tsx

https://app.clickup.com/t/86dx5jbzw

fix: avoid import text overlay on small height screens

---

src/app/lib/mainsail/network.test.ts
src/app/lib/mainsail/networks/mainsail.devnet.ts
src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRowMobile.test.tsx.snap
src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap

Closes: https://app.clickup.com/t/86dx9ahbd
This PR updates explorer URL for Mainsail network.

chore: update explorer URL

---

src/domains/transaction/components/TransactionDetail/TransactionDetails/TransactionDetails.tsx

Closes: https://app.clickup.com/t/86dxcw34q

fix: tx block status font weight

---

src/domains/transaction/components/FeeField/__snapshots__/FeeField.test.tsx.snap
src/domains/transaction/components/InputFee/InputFee.contracts.ts
src/domains/transaction/components/InputFee/InputFee.tsx
src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
src/domains/transaction/components/InputFee/blocks/InputFeeAdvanced.tsx
src/domains/transaction/components/InputFee/blocks/InputFeeSimple.tsx
src/domains/transaction/components/InputFee/use-confirmation-times.tsx
src/domains/transaction/components/ValidatorRegistrationForm/__snapshots__/ValidatorRegistrationForm.test.tsx.snap
src/domains/transaction/pages/SendTransfer/SendTransfer.Fees.test.tsx
src/domains/transaction/pages/SendValidatorResignation/__snapshots__/SendValidatorResignation.test.tsx.snap

Closes https://app.clickup.com/t/86dxe6jpu

feat: use block time estimates on fees

---

src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionAddresses.test.tsx
src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionAddresses.tsx
src/domains/transaction/components/TransactionDetail/TransactionAddresses/TransactionRecipient.tsx
src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
src/domains/transaction/pages/SendTransfer/LedgerReview.tsx
src/domains/transaction/pages/SendTransfer/ReviewStep.tsx

https://app.clickup.com/t/86dxg86p8

refactor: show multiple (1) for single multipayment recipient

---

src/app/i18n/common/i18n.ts
src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.test.tsx
src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.tsx
src/domains/vote/i18n.ts
src/domains/wallet/components/SearchWallet/SearchWallet.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.test.tsx
src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx

https://app.clickup.com/t/86dxg7nau

refactor: add disabled due to insufficient balance tooltip

---

src/app/components/Modal/Modal.tsx
src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap

Closes https://app.clickup.com/t/86dxf9ctw
Preview:

refactor: add top offset on wallet name edit modal  on mobile

---

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowId.tsx
src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap
src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap

- Addressing column width has been adjusted to prevent it from overlapping with the amount column.
- Method column width has been reduced in the 768px view to give more space to the amount and addressing columns.
- "A few seconds ago" label has been adjusted to prevent it from wrapping in multiple lines.
- The number of characters to display in the pending and error transaction id badges has been increased to take advantage of the increased width we have.
- Test snapshots have been updated to match these changes.
- Position of the copy button for the addressing column won't overlap with the next column, since now the column width for the addressing has been adjusted to `w-fit`.
## Screenshots
- 768px:
- 1024px:
- 1280px:

fix: transactions table UI adjustments

---

src/app/contexts/Ledger/hooks/connection.ts
src/app/lib/mainsail/ledger.service.ts
src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.tsx
src/domains/message/components/SignMessage/SignMessageSidePanel.tsx
src/domains/portfolio/components/ImportWallet/Ledger/LedgerConnectionStep.tsx
src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
src/domains/transaction/pages/SendTransfer/SendTransfer.tsx

Closes: https://app.clickup.com/t/86dxjb6gf
[Screencast from 2025-08-22 17-08-10.webm](https://github.com/user-attachments/assets/eaa8145f-6c44-4e06-8515-c570af375cd6)

fix: transaction sending with ledger address

---

package.json

Closes: https://app.clickup.com/t/86dxkbvfu
Pins node version to be 22.x

chore: limit node version

---

src/domains/transaction/components/SendTransferSidePanel/SendTransferSidePanel.tsx

Closes: https://app.clickup.com/t/86dxkbxue

fix: hide subtitle when ledger address sending tx

---

.github/workflows/test.yml
src/domains/transaction/components/SendVoteSidePanel/SendVoteSidePanel.Combined.test.tsx
src/domains/transaction/components/SendVoteSidePanel/SendVoteSidePanel.Encryption.test.tsx
src/domains/transaction/components/SendVoteSidePanel/SendVoteSidePanel.Keyboard.test.tsx
src/domains/transaction/components/SendVoteSidePanel/SendVoteSidePanel.test.tsx
src/domains/transaction/components/SendVoteSidePanel/SendVoteSidePanel.tsx
src/domains/transaction/components/SendVoteSidePanel/__snapshots__/SendVoteSidePanel.test.tsx.snap

https://app.clickup.com/t/86dxkhj0k

test: send vote side panel test coverage

---

src/app/lib/mainsail/transaction.service.ts

Related to https://app.clickup.com/t/86dxkbjr8
Fixes double-signing prompt for vote swaps with ledger wallets. 
When a vote is a swap, we can only include the new voting address, ignoring the unvotes.

refactor: change unvote + vote to single vote transaction

---

.env.example
src/app/lib/profiles/contracts.ts
src/app/lib/profiles/profile.importer.ts
src/app/lib/profiles/profile.mainsail-migrator.contract.ts
src/app/lib/profiles/profile.mainsail-migrator.test.ts
src/app/lib/profiles/profile.mainsail-migrator.ts
src/app/lib/profiles/profile.repository.ts

first part of https://app.clickup.com/t/86dwq8uch - covers migrating existing .wwe files to work in the Mainsail version of Vault

feat: profile import migration

---

src/app/hooks/use-search-parameters-validation.tsx
src/app/lib/mainsail/networks/mainsail.mainnet.test.ts
src/app/lib/mainsail/networks/mainsail.mainnet.ts

Closes https://app.clickup.com/t/86dxmuz21

fix: update nethash in devnet manifest config

---

src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
src/domains/transaction/components/LedgerConfirmation/LedgerConfirmation.test.tsx
src/domains/transaction/components/LedgerConfirmation/LedgerConfirmation.tsx
src/domains/transaction/components/LedgerConfirmation/__snapshots__/LedgerConfirmation.test.tsx.snap
src/domains/transaction/i18n.ts

Closes https://app.clickup.com/t/86dxnrekd

refactor: improve ledger approval alert message

---

src/domains/wallet/components/MnemonicList/MnemonicList.tsx

Closes https://app.clickup.com/t/86dxurndc

fix: prevent app from crashing when exiting create wallet flow

---

src/app/lib/profiles/profile.contract.ts
src/app/lib/profiles/profile.test.ts
src/app/lib/profiles/profile.ts
src/domains/portfolio/components/CreateWallet/CreateAddressSidePanel.tsx
src/domains/wallet/hooks/use-import-options.tsx

Closes: https://app.clickup.com/t/86dxv33uf
This enables HD wallets in development _alike_ environements.

chore: enable HD wallets in development

---

src/app/components/SidePanel/SidePanel.tsx
src/app/i18n/common/i18n.ts

https://app.clickup.com/t/86dxthybb

feat: add minimize flow on side-panel
