src/domains/setting/pages/Export/Export.tsx, src/domains/setting/pages/Export/__snapshots__/Export.test.tsx.snap, src/domains/setting/pages/Networks/Networks.tsx, src/domains/setting/pages/Networks/__snapshots__/Networks.test.tsx.snap, src/domains/setting/pages/Networks/blocks/CustomNetworksList.tsx, src/domains/setting/pages/Servers/Servers.test.tsx, src/domains/setting/pages/Servers/Servers.tsx, src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap, src/domains/setting/pages/Servers/blocks/CustomPeers.tsx, src/domains/transaction/pages/SendTransfer/NetworkStep.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.NetworkSelection.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx, src/domains/wallet/components/NetworkStep/NetworkStep.tsx, src/domains/wallet/pages/CreateWallet/ConfirmPassphraseStep.tsx, src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
Closes #31.
Adds a divider to:
- export, network and server settings
- network step of create / import wallet forms
- network step of transaction form
- mnemonic verification step
=> refactor: add missing divider to forms

src/domains/wallet/pages/WalletDetails/hooks/use-wallet-options.ts
The history option is currently not available for wallets that have transactions but no balance.
=> refactor: show transaction history options also if balance is zero

src/domains/setting/pages/Networks/Networks.tsx
Closes https://app.clickup.com/t/2kj7a4j
-   [x] Documentation _(if necessary)_
=> fix: sync profile networks after adding custom network

.github/workflows/test.yml, scripts/generate-test-workflow.js
Having multiple attempts was useful when individual jobs couldn't be executed in isolation once they failed, which has now been possible for a while. As of now it just means the whole workflow takes forever to definitely fail.
=> ci: set maximum attempts of jobs to 1

src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
Restores the UX change in `AddRecipient` component introduced by https://github.com/ArdentHQ/arkvault/pull/102.
When adding recipient + amount and switching to multiple recipient form (using the toggle) the recipient should not be automatically added, but instead, the data should be filled in the multiple-recipient form inputs requiring from the user to click  "Add Recipient" button to add the recipient.
Example:
https://user-images.githubusercontent.com/22020168/180481769-24a8f094-1f32-4903-9667-856d36dd29e3.mp4
-   [x] Tests …
=> fix: restore `AddRecipient` toggle ux to previous state

src/domains/transaction/pages/SendVote/FormStep.tsx
Part of https://app.clickup.com/t/2r1bejb
Always show input fields for network and sender in votes form. Currently, both fields are disabled. 
Example:
=> refactor: use input fields in `SendVote` form step

src/app/components/QRFileUpload/QRFileUpload.test.tsx, src/app/components/QRFileUpload/QRFileUpload.tsx, src/app/components/QRModal/QRModal.test.tsx, src/app/components/QRModal/QRModal.tsx, src/domains/transaction/i18n.ts
https://app.clickup.com/t/2unj6kg
Instead of showing the QR errors inside the viewfinder, this PR implements them as toasts.
=> refactor: implement qr errors as toasts

src/styles/toasts.css
The toasts, especially on mobile, are positioned slightly wrong - they should stick to the bottom and sides. Probably a remainder of the recent toastify upgrade.
=> refactor: adjust positioning and paddings of toasts

src/app/hooks/use-validation.ts, src/domains/wallet/components/SignMessage/FormStep.tsx, src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/wallet/validations/SignMessage.ts, src/domains/wallet/validations/index.ts
Limits the message input in the sign message modal to 600 characters.
=> refactor: limit message signing to 600 characters

src/app/__snapshots__/App.test.tsx.snap, src/app/components/Badge/Badge.styles.ts, src/app/components/Badge/__snapshots__/Badge.test.tsx.snap, src/app/components/FilterNetwork/NetworkOptions.tsx, src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap, src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap, src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/Signatures.tsx
Unselected items are not rendered properly in the network filter component.
=> fix: remove default transparent border from `Badge` component

src/domains/message/pages/SignMessage/SignMessage.test.tsx, src/domains/message/pages/SignMessage/SignMessage.tsx, src/domains/message/validations/SignMessage.ts, src/utils/validations/validate-pattern.test.ts, src/utils/validations/validate-pattern.ts
https://app.clickup.com/t/2w3839j
=> refactor: limit allowed characters to printable ascii when signing with ledger

src/app/hooks/use-profile-synchronizer.test.tsx, src/app/hooks/use-profile-synchronizer.ts
Closes https://app.clickup.com/t/2t1ywax
Filters the notifications to show only for the ones for the available profile networks
=> refactor: only show notifications for wallets in visible networks

src/utils/network-utils.ts
Fixes the network lookup for vote deeplinks for when a network id is used.
=> fix: network lookup in vote deeplink when using id

src/app/components/DeleteResource/DeleteResource.tsx, src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap, src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap, src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap, src/domains/exchange/components/DeleteExchangeTransaction/__snapshots__/DeleteExchangeTransaction.test.tsx.snap, src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap, src/domains/profile/components/PasswordModal/PasswordModal.tsx, src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap, src/domains/profile/components/SignIn/SignIn.tsx, src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap, src/domains/transaction/components/ConfirmRemovePendingTransaction/__snapshots__/ConfirmRemovePendingTransaction.test.tsx.snap, src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap, src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx, src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
This PR increases the width of the following modals:
- DeleteResource (-> Wallet / Contact / Profile)
- SignIn / PasswordModal
- UpdateWalletName
=> chore: increase width of various modals

src/domains/transaction/hooks/use-send-transfer-form.ts, src/domains/transaction/pages/SendTransfer/SendTransfer.contracts.ts, src/domains/transaction/pages/SendTransfer/SendTransfer.helpers.ts
https://app.clickup.com/t/3225caf
=> fix: correct expiration estimate for musig transactions

.github/workflows/deps.yml
Since we're updating, the lockfile will not match and CI defaults to `--frozen-lockfile`
=> fix: use explicit --no-frozen-lockfile for dep update workflow

src/domains/transaction/i18n.ts, src/domains/transaction/validations/SendTransfer.test.tsx, src/domains/transaction/validations/SendTransfer.ts
https://app.clickup.com/t/3a3859t
=> refactor: invalidate migration address in regular transfer flow

src/domains/wallet/pages/ImportWallet/ImportWallet.Validations.test.tsx, src/domains/wallet/pages/ImportWallet/MethodStep.tsx
Closes https://app.clickup.com/t/8677axr6a
If the secret that is validated is bip39 compliant, the form shows the respective error prompting to use the mnemonic method, otherwise, it shows the actual error returned from sdk.
=> fix: adjust bip39 error message in secret validation when importing wallet 

src/domains/profile/pages/ImportProfile/ProfileFormStep.tsx
=> fix: ensure profile avatar is always set when importing profile

src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
Related: https://app.clickup.com/t/86dt5qa1x
Depends on: https://github.com/ArdentHQ/platform-sdk/pull/58/files
=> refactor: delegate table username/rank adjustments

src/domains/transaction/components/InputFee/InputFee.helpers.test.tsx, src/domains/transaction/components/InputFee/InputFee.helpers.ts, src/domains/transaction/components/InputFee/blocks/InputFeeAdvanced.tsx
Closes https://app.clickup.com/t/86dt3t15h
=> fix: input stepper decrementing issues

src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/hooks/use-send-transfer-form.ts, src/domains/transaction/pages/SendTransfer/SendTransfer.contracts.ts, src/domains/transaction/validations/SendTransfer.ts
Close https://app.clickup.com/t/86dt3t18h
=> fix: increasing custom fees available balance

src/app/components/Alert/Alert.styles.ts, src/app/components/Alert/__snapshots__/Alert.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Closes comment on https://app.clickup.com/t/86dt1nuk1
=> fix: collapsible alert dark mode chevron color

src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.tsx, src/domains/transaction/pages/SendDelegateResignation/FormStep.tsx, src/domains/transaction/pages/SendDelegateResignation/SummaryStep.tsx
Closes: https://app.clickup.com/t/86dt8x4q4
> since the resignation no longer has a username asset, we should hide this field on the mainsail networks where it doesn't exist
For Ark network addresses have to have a username to see the validator resignation step, so as a solution I hid the username field if username doesn't exist. 
When an address doesn't have a username:
When an address has a username:
Detail:
Resign Tx summary:
=> refactor: hide username for validator resignation

src/app/hooks/use-validation.ts, src/domains/transaction/components/DelegateRegistrationForm/FormStep.tsx, src/domains/transaction/validations/DelegateRegistration.ts
Additional adjustments for https://app.clickup.com/t/86dt8g7cu to resolve prop drilling for network parameter in delegate validation hook. Network parameter is only passed in `delegateRegistration.username()` where is needed.
=> refactor: adjust network param handling in delegate validation

src/app/components/Input/InputCurrency.tsx
Issue described on ticket is caused by the value being sanitized while typing, the adjustment applies the decimals limit sanitization until input is blurred
Other than testing, ensure that this does not cause any side-effect on other places when the currency input is used
https://app.clickup.com/t/86dtace5v
=> fix: prevent sanitizing issues on currency input

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx, src/domains/transaction/i18n.ts
- The implementations of `Switch vote` have been renamed to `Vote swap`
=> refactor: rename switch vote to vote swap

.github/workflows/snapshots.yml
Adjusts the workflow to continue even on errors during the `pnpm test` step
=> chore: allow snapshots to update on failure

src/app/components/Header/HeaderSearchBar/HeaderSearchBar.contracts.tsx, src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx, src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx, src/domains/transaction/components/SearchRecipient/SearchRecipient.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx
- `HeaderSearchBar` component has been refactored and now supports the option to always display the `clear` button.
- Recipient and Sender search bars have been updated to always display this button ignoring if they have content or not.
- Styles for the search bar have been updated.
=> refactor: address search box

src/app/components/DetailWrapper/DetailWrapper.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/LedgerReview.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap, src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
- Long memos will now break into multiple lines instead of overflowing the texts.
- Snapshots for UTs have been updated.
=> fix: long memo overflow

src/app/components/Table/TableWrapper.tsx, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap, src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.tsx, src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.tsx, src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
- Table padding and borders have been refactored to match the new designs.
- `TableWrapper` styles have been refactored.
- Skeleton scan table:
- Wallet scan table:
- Imported wallets table:
=> refactor: ledger tables padding

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/PendingTransferRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/SignedTransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap
- Border for transaction type label in dark mode has been fixed.
- Also, the padding and height for this label has been adjusted to match the designs.
=> fix: transaction label border in dark mode

src/app/components/Amount/AmountLabel.tsx, src/app/components/Amount/__snapshots__/AmountLabel.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRow.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRowMobile.test.tsx.snap, src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/SentStep.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionAmount/__snapshots__/TransactionAmount.test.tsx.snap, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransactionSuccessful/__snapshots__/MultiSignatureSuccessful.test.tsx.snap, src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMobile.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowAmount.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowMobile.test.tsx.snap, src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/__snapshots__/UnconfirmedTransactionTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/transaction/components/UnlockTokens/blocks/UnlockTokensSelect/__snapshots__/UnlockTokensSelect.test.tsx.snap, src/domains/transaction/components/UnlockTokens/blocks/UnlockTokensSelect/__snapshots__/UnlockTokensTotal.test.tsx.snap, src/domains/transaction/components/UnlockTokens/blocks/__snapshots__/UnlockTokensReview.test.tsx.snap, src/domains/transaction/components/UnlockTokens/blocks/__snapshots__/UnlockTokensSummary.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.Fees.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
- The height of the amount label has been fixed in the transaction rows.
=> fix: amount label height in transaction row

src/app/components/Link/Link.tsx, src/app/components/Link/__snapshots__/Link.test.tsx.snap
Closes https://app.clickup.com/t/86dux5gwx 
=> fix: use inner group to scope hover state in link component

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/wallet/components/PortfolioHeader/PortfolioHeader.tsx, src/domains/wallet/components/PortfolioHeader/__snapshots__/PortfolioHeader.test.tsx.snap, src/domains/wallet/components/WalletsGroup/__snapshots__/WalletsGroup.test.tsx.snap
Closes: https://app.clickup.com/t/86dux5t9u
Added a task to fix other paddings: https://app.clickup.com/t/86dux6jfm
=> fix: portfolio header padding

src/app/components/Tabs/Tabs.tsx
Closes https://app.clickup.com/t/86dux79a1
=> fix: correct tab border colors in dark mode

src/domains/dashboard/components/PortfolioBreakdown/PortfolioBreakdown.tsx, src/domains/wallet/components/PortfolioHeader/PortfolioHeader.tsx, src/domains/wallet/pages/CreateWallet/ConfirmPassphraseStep.tsx
Closes: https://app.clickup.com/t/86dux6jfm
This PR is about this part of the page: 
=> fix: portfolio breakdown padding

src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx, src/domains/transaction/components/TransactionDetail/TransactionSummary/TransactionSummary.tsx
Closes: https://app.clickup.com/t/86dux77th
=> fix: adjust font weight of total amount in transaction summary

src/app/components/Input/Input.tsx
Closes https://app.clickup.com/t/86duxjaue
=> fix: correct input text color in light mode

src/app/components/Modal/Modal.tsx, src/domains/exchange/components/ExchangeForm/ConfirmationStep.tsx, src/domains/exchange/components/ExchangeForm/__snapshots__/ExchangeForm.test.tsx.snap
- The width for the explorer link container has been fixed in the exchange completed view.
=> fix: truncation on confirmation step

src/domains/exchange/components/ExchangeForm/ExchangeForm.tsx
- `useEffect` hook used to update the step has been fixed so it can't update after being on the success step.
https://github.com/user-attachments/assets/f3784fb8-d7fc-41fc-afe4-d8f1665389df
=> fix: prevent success step to change tab

src/app/components/WalletListItem/WalletListItem.blocks.tsx, src/domains/wallet/components/SearchWallet/SearchWallet.tsx, src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
- Truncation has been added for the wallet name.
- Max width has been set for the wallet name in desktop view.
=> fix: transaction sender modal truncation

src/app/components/Amount/__snapshots__/AmountLabel.test.tsx.snap, src/app/components/Label/Label.styles.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/transaction/components/TransactionTable/PendingTransactionsTable/__snapshots__/PendingTransactionsTable.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap, src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap, src/domains/transaction/components/Transactions/__snapshots__/Transactions.test.tsx.snap, src/domains/transaction/components/UnlockTokens/blocks/UnlockTokensSelect/__snapshots__/UnlockTokensSelect.test.tsx.snap
- Hover style for labels has been refactored in both dark and light mode.
- Padding for row in transaction table has also been fixed.
=> refactor: label hover style

src/app/components/Card/Card.tsx, src/app/components/Card/__snapshots__/Card.test.tsx.snap, src/app/components/PageSkeleton/__snapshots__/PageSkeleton.test.tsx.snap, src/app/components/WalletListItem/WalletListItemSkeleton.tsx, src/app/components/WalletListItem/__snapshots__/WalletListItemSkeleton.test.tsx.snap, src/domains/contact/components/ContactListMobile/ContactListItemMobile.tsx, src/domains/contact/components/ContactListMobile/__snapshots__/ContactListItemMobile.test.tsx.snap, src/domains/contact/components/ContactListMobile/__snapshots__/ContactListMobile.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/profile/components/ProfileRow/ProfileRow.tsx, src/domains/profile/components/ProfileRow/__snapshots__/ProfileRow.test.tsx.snap, src/domains/setting/pages/Networks/blocks/CustomNetworksList.tsx, src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap, src/domains/setting/pages/Servers/blocks/CustomPeers.tsx, src/domains/wallet/components/WalletsList/__snapshots__/WalletsList.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx, src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
- The 3 dots icon size has been updated for the wallet header. The icon has also been updated and now has the dots filled.
- Other implementations for the icon have also been updated in:
- Custom peer cards (in settings)
- Custon network icons (in settings)
- Skeleton loaders (for the wallet header and profile cards)
=> refactor: update three dots icon size

src/domains/exchange/components/ExchangeTransactionsTable/ExchangeTransactionsRow.tsx, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRow.test.tsx.snap
- The background hover styles for the exchange transactions table has been updated in tablet view to prevent it from breaking.
=> fix: exchange table row hover styles

src/domains/transaction/components/FilterTransactions/FilterTransactions.tsx
https://app.clickup.com/t/86dv5gp62
=> fix: restore filter dropdown shadow

src/app/components/Accordion/Accordion.test.tsx, src/app/components/Accordion/__snapshots__/Accordion.test.tsx.snap, src/app/hooks/use-accordion.ts, src/domains/contact/components/ContactListMobile/ContactListItemMobile.test.tsx, src/domains/contact/components/ContactListMobile/__snapshots__/ContactListItemMobile.test.tsx.snap, src/domains/contact/components/ContactListMobile/__snapshots__/ContactListMobile.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/pages/Dashboard/Dashboard.WalletActions.test.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/setting/pages/Servers/Servers.test.tsx, src/domains/setting/pages/Servers/__snapshots__/Servers.test.tsx.snap, src/domains/wallet/components/PortfolioHeader/__snapshots__/PortfolioHeader.test.tsx.snap, src/domains/wallet/components/WalletsGroup/WalletsGroup.test.tsx, src/domains/wallet/components/WalletsGroup/__snapshots__/WalletsGroup.test.tsx.snap
- `use-accordion` has been refactored and it will now be opened by default.
- This change will be reflected on wallet accordions (as seen in image), contacts list (in mobile), and custom peers accordion.
=> refactor: set accordions opened by default

src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.test.tsx
- The transaction fixture for the flaky unit test in `src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.test.tsx` has been refactored to prevent the test from randomly failing.
=> fix: flaky transaction test

src/app/components/Accordion/__snapshots__/Accordion.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap, src/domains/transaction/components/MultiSignatureDetail/__snapshots__/SentStep.test.tsx.snap, src/domains/transaction/components/TransactionDetail/TransactionSummary/TransactionSummary.tsx, src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionAmount.blocks.tsx, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.Fees.test.tsx.snap, src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Closes https://app.clickup.com/t/86dv7tyza
=> refactor: adjust font size in transaction detail amount

src/domains/transaction/components/TransactionExportModal/TransactionExportForm/BasicSettings.tsx, src/domains/transaction/components/TransactionExportModal/TransactionExportForm/CsvSettings.tsx
Closes https://app.clickup.com/t/86dv94xyy
=> fix: increase z index in transaction history date dropdown

src/app/components/Address/AddressLink.tsx, src/app/components/Amount/__snapshots__/AmountLabel.test.tsx.snap, src/app/components/Label/Label.styles.tsx, src/app/components/Label/__snapshots__/Label.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap, src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap, src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap, src/domains/exchange/components/ExchangeForm/__snapshots__/ExchangeForm.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRow.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRowMobile.test.tsx.snap, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
- Font ligatures have been removed from the following components:
- Address link
- Labels
- This will prevent the x from being placed in the middle when having numbers on the address.
1. Address link
2. Labels
=> refactor: remove ligatures from addresses

vite.config.ts, vitest.config.ts
Closes https://app.clickup.com/t/86dvn155b
Fixes sourcemap warnings in tests 
=> chore: ignore psdk sourcemaps

src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.Keyboard.test.tsx
Fixes an `act` error that appeared in wallet domain, spotted in https://github.com/ArdentHQ/arkvault/actions/runs/12808742552/job/35712994174?pr=894#step:9:1075
=> chore: fix `act` warning in wallet domain

src/domains/dashboard/pages/Dashboard/Dashboard.tsx
Closes https://app.clickup.com/t/86dvvbch0 
=> fix: show portfolio header only when profile has wallets

src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
- `p` tag has been replaced with a `div` to prevent semantic issue when having no votes in a wallet.
=> fix: semantic issue when having no vote

src/app/contexts/Ledger/hooks/import.ts, src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx, src/domains/wallet/pages/CreateWallet/CreateWallet.tsx, src/domains/wallet/pages/ImportWallet/ImportWallet.tsx, src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.test.tsx, src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.Keyboard.test.tsx, src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.test.tsx, src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap, src/domains/wallet/utils/get-default-alias.test.ts, src/domains/wallet/utils/get-default-alias.ts
- `get-default-alias` hook has been refactored to set the name of new addresses imported regardless of the network.
- Unit tests have been added and refactored to support this change.
=> refactor: change default labels

src/app/components/Table/Mobile/MobileCard.tsx, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionTable.test.tsx.snap, src/domains/exchange/components/ExchangeTransactionsTable/__snapshots__/ExchangeTransactionsRowMobile.test.tsx.snap, src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
Closes https://app.clickup.com/t/86dvx2kwt 
Fixes wrong background colors in dark mode, for mobile & small devices for transaction rows:
=> fix: correct dark background color on tx rows mobile views

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx, src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
Closes https://app.clickup.com/t/86dvvnq9x
Previews:
=> fix: make transaction row addresses occupy available space

src/domains/dashboard/pages/Dashboard/Dashboard.tsx
- Page title for Portfolio has been renamed to simply `Portfolio`
=> refactor: portfolio page title

src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.blocks.tsx, src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
- The resigned label has been refactored and assigned the `solid` variant to adjust its colors.
=> fix: resigned label color

src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
- `text-nowrap` class has been added to table headers, as a result the table headers will stop breaking in many lines.
- 
=> fix: add nowrap to table headers

src/app/components/PageSkeleton/ProfilePageSkeleton.tsx, src/app/components/PageSkeleton/__snapshots__/ProfilePageSkeleton.test.tsx.snap
- Navbar skeleton has been refactored to match the new redesign in both the mobile and desktop version
- Mobile:
- Desktop:
=> refactor: initial loading screen navbar

src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx, src/domains/transaction/pages/SendVote/SendVote.tsx
- The `Back to wallet` button redirection has been fixed for both the `Vote` and `Transfer` transaction flows.
https://github.com/user-attachments/assets/65af4a68-a547-49e2-bf32-7fb79ce34092
=> fix: back to wallet redirection

src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx, src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRow.test.tsx.snap, src/domains/transaction/components/TransactionTable/TransactionTable.helpers.tsx
- Spacing in the transactions table has been fixed to prevent overlays between the columns in desktop views when a single wallet is selected.
- 960px:
- 1024px:
- 1280px:
- +1300px:
=> refactor: adjust transactions table spacing

src/app/components/SidePanel/SidePanel.tsx
- Backdrop blur of 24px has been added to the overlay container in side panels to match the designs.
=> refactor: sidepanel blur effect

src/app/services/ToastService.tsx
- Toast messages have been centered so it can be reviewed to see how it looks and feels.
## Screenshots
=> refactor: move toast position to bottom left

src/domains/portfolio/components/ImportWallet/ImportAddressSidePanel.tsx, src/domains/portfolio/components/ImportWallet/ImportDetailStep.tsx
Closes: https://app.clickup.com/t/86dw5xcwe
This PR improves the import flow, changes are:
Removes added wallets when:
- user navigates back to the enter mnemonic step from the enter password step
- user closes sidebar early
and fixes the original issue: it handles the case when user enters an invalid password and then navigates back to the enter mnemonic screen
[Screencast from 2025-03-07 18-43-25.webm](https://github.com/user-attachments/assets/fce3c9e8-de6e-4f89-aa1f-4f40e0ed899c)
-   [ ] Ready …
=> refactor: improve import flow

src/app/components/SidePanel/SidePanel.tsx
- Mouse action to close the slide menus has been changed from `mousedown` to `pointerdown` to prevent the side panels from closing while using them on iOS devices.
https://github.com/user-attachments/assets/c5cd7189-43fb-449b-9297-76ae851745f8
=> fix: ios sidepanel click

src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/pages/SendTransfer/FormStep.tsx, src/domains/transaction/pages/SendTransfer/ReviewStep.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
As a part of: https://app.clickup.com/t/86dw6qy8m
This PR moves fee options to the review step for transfer tx, also adjusts `Send All` button to deduct `5*21_000` before setting amount.
=> refactor: move fee input to review step for transfer transactions

src/domains/message/pages/SignMessage/SignMessage.tsx, src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/message/pages/VerifyMessage/VerifyMessage.tsx, src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/transaction/pages/SendRegistration/SendRegistration.tsx, src/domains/transaction/pages/SendTransfer/SendTransfer.tsx, src/domains/transaction/pages/SendUsernameResignation/SendUsernameResignation.tsx, src/domains/transaction/pages/SendValidatorResignation/SendValidatorResignation.tsx, src/domains/transaction/pages/SendVote/SendVote.tsx, tailwind.config.js
- A new value in tailwind config has been added for max width: `172` (43rem).
- The max width for the forms, review, authentication, pending and confirmed steps for the following transaction types has been updated from `576px` to `688px`:
- Transfer
- Vote
- Sign/Verify message
- Username registration
=> refactor: transactions pages width increase

src/app/components/Input/InputPassword.tsx, src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap, src/app/components/PasswordValidation/__snapshots__/PasswordValidation.test.tsx.snap, src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap, src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap, src/domains/wallet/components/EncryptPasswordStep/__snapshots__/EncryptPasswordStep.test.tsx.snap
- The hide/view icon color has been adjusted in light mode to `gray-700` for password inputs.
=> refactor: input password icon color

src/domains/portfolio/components/ImportWallet/ImportAddressSidePanel.tsx
Closes: https://app.clickup.com/t/86dw7npnr
This PR adjusts import flow to prevent early form submit when `enter` key pressed.
Testing:
- Open up the `Import` side panel
- Pick a way of import
- Fill the value and press `enter` - you should get navigated to the next step
=> fix: handle `enter` key in import flow

src/app/components/Dropdown/DropdownItem.tsx
- Margin in X axis has been added to the dropdown items hover state.
=> fix: dropdown hover state margin

src/domains/portfolio/components/CreateWallet/ConfirmPassphraseStep.tsx, src/domains/portfolio/components/CreateWallet/EncryptionPasswordStep.test.tsx, src/domains/portfolio/components/ImportWallet/ImportAddressSidePanel.tsx, src/domains/portfolio/components/ImportWallet/ImportDetailStep.tsx, src/domains/portfolio/components/ImportWallet/ImportWallet.Methods.test.tsx, src/domains/portfolio/components/ImportWallet/ImportWallet.Mnemonic.test.tsx, src/domains/portfolio/components/ImportWallet/ImportWallet.Validations.test.tsx, src/domains/wallet/components/CreateAddressSidePanel/CreateAddressSidePanel.test.tsx, src/domains/wallet/components/CreateAddressSidePanel/CreateAddressSidePanel.tsx, src/domains/wallet/components/WalletEncryptionBanner.tsx/WalletEncryptionBanner.test.tsx, src/domains/wallet/components/WalletEncryptionBanner.tsx/WalletEncryptionBanner.tsx, src/domains/wallet/components/WalletEncryptionBanner.tsx/index.ts, src/domains/wallet/i18n.ts
- Wallet encryption toggle has been redesigned. A new `WalletEncryptionBanner` component has been created containing the new design, replacing both implementations in the `Create` and `Import` wallet flows.
- With this new toggle, a new `Accept Responsibility` checkbox has been introduced and registered into the forms, which is now required to continuing registered the wallets.
- Dark mode designs have also been updated for this component.
- Unit tests and translation files have been updated.
- …
=> refactor: wallet encryption toggle

src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx, src/domains/transaction/components/AddRecipient/AddRecipient.tsx, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
- "Send All" button has been moved to the other side of the "Amount" label.
- Also, the selected wallet balance has been moved to respect the designs.
- This has also been updated in dark mode to support the design changes.
- New unit tests to support these changes.
- Snapshots have been updated.
- Single transfer:
- Multiple transfer:
=> refactor: move send all button

src/domains/portfolio/components/AddressesSidePanel/AddressesSidePanel.tsx
- Button variant for "Manage" button has been changed to `primary-transparent`.
- Padding has been adjusted to match the designs.
=> refactor: manage button hover state

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx
- Address switch button has been refactored to now support the `primary-transparent` button styles.
=> refactor: address switch button hover state

src/app/components/SidePanel/SidePanel.tsx, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx
Closes: https://app.clickup.com/t/86dw9yxv3
I think for this specific issue we should apply a local solution because there are not many tooltips with `Got It` button. Since `tippy` appends its root to the parent element I only had to reduce parent's `z-index` to `30`, that will cancel out tippy's `z-index: 9999`.  
[Screencast from 2025-03-20 02-13-34.webm](https://github.com/user-attachments/assets/9adbee04-3cda-428f-a4ed-7e2128fba0d1)
=> fix: onboarding message z ordering

src/app/components/Dropdown/Dropdown.contracts.ts, src/app/components/Dropdown/Dropdown.helpers.tsx, src/app/components/Dropdown/Dropdown.tsx, src/app/components/Dropdown/DropdownItem.tsx, src/domains/transaction/components/TransactionExportModal/TransactionExportForm/CsvSettings.tsx
- Support for `variant` prop has been added for the dropdown render helpers.
- Styles have been updated for `options` variant in the dropdown `Wrapper` and `Item` components.
- The double check icon is now displayed for the selected option in this variant of the dropdown.
=> refactor: options dropdown styling

src/domains/portfolio/components/ImportWallet/ImportAddressSidePanel.tsx
Alternative of https://github.com/ArdentHQ/arkvault/pull/1096 to reset the imported wallet state when closing the side panel 
Task: https://app.clickup.com/t/86dwa3crp
=> fix: reset import state when closing side panel

src/app/components/SidePanel/SidePanel.tsx
- The background color and blur effect has been adjusted for dark mode to match the difference we have in Dashbrd.
## Screenshots
- Dashbrd:
- Arkvault:
=> fix: sidepanel wrapper blur

.github/workflows/snapshots.yml
this will make the reference unique per branch. Right now it will cancel any other snapshot workflows when triggered from the workflow dispatch button as head_ref does not work well with that. Instead `github.ref` should allow us to run them for multiple branches at the same time, while it still cancels the workflow when triggered more than once on the same branch
=> chore: use github.ref over head_ref for concurrency

src/domains/vote/pages/Votes/Votes.tsx
- Votes are now synced when updating the profile and selected wallet from the votes page.
=> fix: sync on import for votes page

src/domains/exchange/components/SendExchangeTransfer/SendExchangeTransfer.Ledger.test.tsx
Closes https://app.clickup.com/t/86dvn57rn
=> refactor: enable exchange send transfer tests

src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap, src/app/components/NavigationBar/NavigationBar.blocks.tsx, src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap, src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap, src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap, src/domains/message/pages/SignMessage/__snapshots__/SignMessage.test.tsx.snap, src/domains/message/pages/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap, src/domains/setting/pages/Export/__snapshots__/Export.test.tsx.snap, src/domains/setting/pages/General/__snapshots__/General.test.tsx.snap, src/domains/setting/pages/Password/__snapshots__/Password.test.tsx.snap, src/domains/transaction/pages/SendValidatorResignation/__snapshots__/SendValidatorResignation.test.tsx.snap, src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
- A random `´` character was being rendered below the navbar buttons and has now been removed from the codebase.
- Snapshots have been updated to support this change.
=> fix: remove comma from navbar

src/domains/message/pages/VerifyMessage/VerifyMessage.test.tsx, src/domains/message/pages/VerifyMessage/VerifyMessage.tsx
Closes: https://app.clickup.com/t/86dwhcawt
`Back` button in Verify page now redirects to `/dashboard`
=> fix: handle back button in verify page

src/domains/wallet/components/WalletEncryptionBanner.tsx/WalletEncryptionBanner.tsx
- `overflow-hidden` class name is being applied only when wallet encryption toggle is enabled, this will prevent the issue when tabbing inside the wallet encryption banner.
https://github.com/user-attachments/assets/cfd8e58f-0e40-4cf9-89ee-ce1ce5d84b4b
=> fix: wallet encryption disappear

src/domains/transaction/components/TransactionDetail/TransactionDetails/TransactionDetails.tsx, src/domains/transaction/hooks/use-block-height.ts
- `blockId` prop has been renamed to `blockHash` in `useBlockHeight` hook.
- `data.height` has been updated to `data.number` in API response, to prevent `NaN` from appearing.
=> fix: block height shown as nan

src/domains/message/pages/SignMessage/SignMessage.tsx
- Class names applied to the div wrapper have been moved to the button class name container in `Clipboard` button variant.
=> fix: sign message button hover state

src/domains/transaction/components/FeeField/FeeField.tsx
- Multipayment transactions constantly started failing providing errors related to the gas limit being lower than expected for the pre-verification of the transaction. This amount, fluctuated betweek 22000 and 23000, reason why in this PR, I am increasing the default gas limit for multipayments to 24 000.
=> fix: increase gas limit for multipayments

src/app/lib/mainsail/networks/mainsail.mainnet.ts
Closes: https://app.clickup.com/t/86dwmufwd
This PR adjusts `mainsail.mainnet` config to use devnet API to resolve the given error: the reason is the ARK public API doesn't have the expected properties. 
Extra: it adjusts mainnet hosts to have all expected APIs in order to fix the error in the console:
=> fix: missing property error when sending a transaction

src/app/lib/sdk/network.ts
- The properties in `network.ts` from the `lib` have been adjusted to match the correct property from the network, allowing users to add recipients again in multipayment transactions. Previously, this wasn't possible due to the `maxRecipients` having a value of 0.
=> fix: unable to add recipients in multipayments

src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx, src/domains/wallet/i18n.ts
- The hint tooltip has been refactored and will now appear when more than one wallet has been imported in single mode.
- Text for single address tooltip has been updated.
=> refactor: onboarding tooltip for single address

src/domains/portfolio/components/ImportWallet/MethodStep.tsx
- `Option` component in `MethodStep` has been refactored to be a `button` component that includes class names for customizing the focus state styles.
=> refactor: accessibility for import wallet

.github/workflows/test.yml, src/app/components/Dropdown/Dropdown.contracts.ts, src/app/components/Dropdown/Dropdown.helpers.tsx, src/app/components/Dropdown/Dropdown.test.tsx, src/app/components/Dropdown/Dropdown.tsx, src/app/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/domains/transaction/components/FilterTransactions/FilterTransactions.tsx, src/domains/vote/components/VotesFilter/VotesFilter.test.tsx, src/domains/vote/components/VotesFilter/VotesFilter.tsx
Closes: https://app.clickup.com/t/86dwrbhz7
- adds focus manager for dropdown
- adds `onKeyDown` handler for tx type filter and validator page dropdowns
- disables focus on `label` for the tx type filter dropdown 
[Screencast from 2025-05-16 17-41-29.webm](https://github.com/user-attachments/assets/dfc3d40a-ac5d-428d-a399-0437697b3eff)
=> refactor: allow tabbing into dropdowns

src/domains/portfolio/components/AddressesSidePanel/AddressesSidePanel.tsx
Closes: https://app.clickup.com/t/86dwt1amt
=> fix: addresses panel mode selector in `xs` screen

src/app/components/Input/Input.tsx, src/app/components/Input/__snapshots__/Input.test.tsx.snap, src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap, src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap, src/app/components/PasswordValidation/__snapshots__/PasswordValidation.test.tsx.snap, src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap, src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap, src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap, src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap, src/domains/setting/pages/General/__snapshots__/General.test.tsx.snap, src/domains/setting/pages/Password/__snapshots__/Password.test.tsx.snap, src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap, src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap, src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap, src/domains/wallet/components/EncryptPasswordStep/__snapshots__/EncryptPasswordStep.test.tsx.snap, src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
- Padding right applied to the icon has been moved out to a parent container that also wraps the tooltip.
- Tooltip position has been fixed and will now appear centered with the input warning icon.
=> fix: tooltip position for input warnings

src/app/lib/mainsail/transaction.service.ts, src/app/lib/profiles/profile.ts, src/app/lib/profiles/wallet.ts, src/domains/message/components/SignMessage/SignMessageSidePanel.test.tsx, src/domains/message/hooks/use-message-signer.ts, src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx, src/utils/assertions.test.ts
https://app.clickup.com/t/86dwwemrm
Notes: the underlying problem is that some of the methods from the `LedgerService` that are called require a `#transport` property to be defined. That property is set using the `connect` method, which we're already calling. The problem is that every time we call the `profile.ledger()` or `wallet.ledger()` method, it returns a new instance. Also, the transaction service uses a new instance, so the transport ends up being undefined. This PR ensures that the same instance is used across services.
-   [ ] Documentation _(if …
=> fix: ledger not signing transactions

.github/workflows/test.yml, src/app/lib/helpers/fast-sort.test.ts, src/app/lib/helpers/filter.test.ts, src/app/lib/helpers/has.test.ts, src/app/lib/helpers/index-of.test.ts, src/app/lib/helpers/slice.test.ts, src/app/lib/helpers/slice.ts, src/app/lib/helpers/unset.test.ts, src/app/lib/helpers/unset.ts, src/app/lib/helpers/validator.test.ts
https://app.clickup.com/t/86dx03r17
100% test coverage for folder, can be tested with `COVERAGE_INCLUDE_PATH=src/app/lib/helpers pnpm test:coverage src/app/lib/helpers`
=> test: increase coverage for `src/app/libs/helpers`

src/app/components/SidePanel/SidePanel.tsx
- Sidepanel's background styling has been adjusted in dim mode to match the designs.
=> refactor: sidepanel background dim

src/app/components/Tooltip/Tooltip.tsx
- Tooltip will now break words if the content is too long in mobile.
=> refactor: improve tooltip on mobile

src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap, src/domains/portfolio/components/PortfolioHeader/PortfolioHeader.tsx
Closes https://app.clickup.com/t/86dx5jbnu
=> fix: show full address on portfolio header on lg

src/domains/portfolio/components/AddressesSidePanel/AddressRow.tsx, src/domains/portfolio/components/AddressesSidePanel/MobileAddressRow.tsx
Closes: https://app.clickup.com/t/86dxcw9be
Single view:
Multiple view:
=> fix: use radios for addresses panel entries in mobile

src/domains/portfolio/components/AddressesSidePanel/DeleteAddressMessage.tsx
Closes: https://app.clickup.com/t/86dxf01ux
Buttons in delete mode should be aligned to the right: https://helloardent.slack.com/archives/C03889W1KHT/p1754389636377679?thread_ts=1754319560.980389&cid=C03889W1KHT
Design: https://www.figma.com/design/OX18z9oCfYiV4cW35bzxsu/ARKVault-Mainsail?node-id=27193-138854&m=dev
=> fix: delete address buttons in addresses side panel

src/domains/message/pages/VerifyMessage/VerifyMessage.test.tsx, src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
Closes https://app.clickup.com/t/86dx2dvkb 
The error seems to be happening because probably the test finishes before `setTimeout` in
https://github.com/ArdentHQ/arkvault/blob/d17c37878c27dcdbebe94e40b3e885aea9061bc6/src/app/hooks/use-input-focus.ts#L24
which is called by several tests in profile creation and message verification.
The PR mocks the `delay` function in thoses tests in order to avoid any delays regarding the input focus/unfocus, though it's not easily reproducible.
=> test: fix flaky tests in profile & message domains

src/domains/transaction/components/AuthenticationStep/Ledger/ListenLedger.tsx, src/domains/transaction/components/AuthenticationStep/Ledger/__snapshots__/ListenLedger.test.tsx.snap
- Scrollbar is now hidden, and the section tag will now take full height to prevent the scrollbar width from appearing and making the content "shake".
=> fix: image shake on Ledger connection step

src/app/hooks/use-search-wallet.test.tsx, src/app/hooks/use-search-wallet.tsx, src/domains/transaction/components/SearchRecipient/SearchRecipient.test.tsx, src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
- The wallet alias is now consistent in the recipient search modal for transactions.
- Unit tests have been updated to increase coverage.
=> fix: wallet alias consistency

src/domains/portfolio/components/ImportWallet/ImportDetailStep.tsx
Closes: https://app.clickup.com/t/86dxj1m54
=> chore: make mnemonic input hint open by default
